---
title: "Elizavetash's project solution"
author: "ManCao"
date: "2023-03-29"
output: md_document
---

```{r setup, include=FALSE}
#packages
library(tidyverse)
library(latticeExtra)

#import
dataRaw<-read.csv("Microplastic_Affect_Soil_Properties_and_Plant_Biomass.csv",header=TRUE,sep=';')
```

## clean data, add biomass

```{r}

dataRaw[dataRaw == ""] <- NA
data<- dataRaw%>%
  drop_na()%>%
  filter(shape=="Films",
         str_detect(root,"^[0-9.]+$"))%>%
  mutate(root = as.numeric(root),
         CO2=gsub("(\\..*)\\.", "\\.", CO2) %>% as.numeric(gsub("\\.", "", CO2))%>% round(2),
         WSA = gsub("(\\..*)\\.", "\\.", WSA) %>% as.numeric(gsub("\\.", "", .)))%>%
  mutate(biomass=root+shoot)

print(data)
```

## plot

```{r} 

p1<- levelplot(biomass~ WSA*CO2,data = data, 
               panel = panel.levelplot.points, 
               cex = 1.2, 
               col.regions = colorRampPalette(c("pink", "blue")),
               main = "Biomass Levelplot") + 
    layer_(panel.2dsmoother(..., n = 200))

p1
```

