---
title: "Solution Attempt"
author: "Sonja"
output: md_document
---

# Table of content

1. [Preparation]    
2. [Data Processing]    
3. [Plot]

# Preparation

```{r, warning=FALSE, message=FALSE}
library(tidyverse)

datRaw <- read.csv2('Microplastic_Affect_Soil_Properties_and_Plant_Biomass.csv', encoding = 'UTF-8') |> 
  rename(shape = X.U.FEFF.shape)

datRaw <- read_csv2('Microplastic_Affect_Soil_Properties_and_Plant_Biomass.csv')
```

# Data Processing

> *Note:* The variable `root` is corrupt, in the sense that it contains a date as well as numbers. Dates have to be excluded.

```{r, warning=FALSE}
dat <- datRaw |> 
  # convert
  mutate(across(c(concentration, root, CO2),
                as.double)) |> 
  # filter polyethylene films and concentrations and remove dates
  filter(shape == 'Films',
         str_detect(root, '\\d$')) |> 
  # generate total biomass
  mutate(root = as.double(root),
         biomass = root + shoot) |> 
  # recode soil aggregation
  mutate(WSA = WSA / 1000) |> 
  # select columns
  select(concentration,
         CO2,
         WSA,
         biomass) |> 
  # drop NAs
  na.omit()
```

# Plot

```{r fig-1, warning=FALSE, message=FALSE, fig.cap="Relationship between Soil Aggregation and Microbial Activity, Colored with the Value of Biomass"}

library(latticeExtra)

levelplot(biomass ~ WSA * CO2, 
          dat,
          panel = panel.levelplot.points,
          scales = list(x = list(at = seq(0, 6500, by = 500))), 
          colorkey = list(title = 'Total Biomass'),
          main = 'Figure 1',
          xlab = 'Soil Aggregation in % (in thousand)',
          ylab = 'Microbial Activity in μg CO2/(g*h)') + 
  layer_(panel.2dsmoother(..., n = 200))
```
