---
title: "Martin's Project Solution"
author: "Minseo Kim"
date: "2026-05-05"
output: html_document
---

```{r setup, include=FALSE}
library(tidyverse)
```

```{r Data Import}
zip_reading<- "C:/Users/minse/OneDrive/Documents/Data-projects-with-R-and-GitHub/Projects/martin-raden/PV"

zip_data<- list.files(zip_reading, pattern="\\.zip$", full.names=TRUE)

zip_data

zip_df<- lapply(zip_data,function(zip_path){
  file_name<-unzip(zip_path, list=TRUE)$Name[1]
  read_csv2(unz(zip_path, file_name))
})

pv_data<-bind_rows(zip_df)

names(pv_data)

```

```{r datatype }
glimpse(pv_data)

#changing yield to dbl

pv_data <- pv_data %>% mutate(
    `PV Ertrag [kWh]` = gsub(";", "", `PV Ertrag [kWh]`),   
    `PV Ertrag [kWh]` = gsub(",", ".", `PV Ertrag [kWh]`),
    `PV Ertrag [kWh]` = as.numeric(`PV Ertrag [kWh]`))

#changing dates to date
pv_data <- pv_data%>%mutate(Datum=as.Date(Datum, format = "%d.%m.%Y"))
```

```{r missing values}

#missing values
sum(is.na(pv_data))

#0 missing values
```

```{r duplicated values}

#duplicated value
sum(duplicated(pv_data))

#only leave the values with higher yield

pv_data<-pv_data%>% group_by(Datum)%>% slice_max(`PV Ertrag [kWh]`,n=1)%>%ungroup()
#Okay this doesnt work apparently, because "sum(duplicated(pv_data)) just counts the whole row to be exactly duplicated. 

#so then, I will have to check it like this

sum(duplicated(pv_data$Datum))

pv_data<- pv_data %>% arrange(Datum,desc(`PV Ertrag [kWh]`))%>%
  distinct(Datum, .keep_all=TRUE)
```

```{r data 2025}
#only 2025 data
pv_data <- pv_data%>% filter(format(Datum, "%Y")=="2025")
```

```{r, adding data}
#Adding on colums 

pv_data <- pv_data %>%
  mutate(`Eigenverbrauch [kWh]` = `PV Ertrag [kWh]` - `Netzeinspeisung [kWh]`- `Speicherung [kWh]`,
         `Gesamtverbrauch [kWh]` = `Eigenverbrauch [kWh]` + `Netzbezug [kWh]`,
         `Eigenverbrauchsanteil [%]` = (`Eigenverbrauch [kWh]` / `Gesamtverbrauch [kWh]`)*100) %>%arrange(Datum)
```

```{r monthly data}
library(dplyr)

monthly_data<-pv_data%>%mutate(Monat= factor(format(Datum,"%B"),levels=month.name))%>%

group_by(Monat)%>%summarise(across(c(`PV Ertrag [kWh]`,`Eigenverbrauch [kWh]` ,`Gesamtverbrauch [kWh]`,`Netzeinspeisung [kWh]`,`Netzbezug [kWh]`),sum))
```

```{r add colums}
monthly_data <- monthly_data %>%
  mutate(
    Stromkosten = `Netzbezug [kWh]` * 0.30,
    Einspeiseverguetung = `Netzeinspeisung [kWh]` * 0.08,
    Einsparung_Eigenverbrauch = `Eigenverbrauch [kWh]` * 0.30,
    Gesamtwirtschaftlichkeit =
      Einsparung_Eigenverbrauch +
      Einspeiseverguetung -
      Stromkosten
  ) %>%
  arrange(Monat) %>%
  mutate(across(where(is.numeric), ~ round(.x, 2)))
```

```{r rename}
monthly_data_table <- monthly_data %>%
  rename(
    `Stromkosten` = Stromkosten,
    `Einspeiseverguetung`= Einspeiseverguetung,
    `Einsparungen durch Eigenverbrauch` = Einsparung_Eigenverbrauch,
    `Gesamtwirtschaftlichkeit` = Gesamtwirtschaftlichkeit
  )

# WHY CAN I NOT PUT EURO SIGN??
# WHY DOESN'T "Ü" WORK??
knitr::kable(monthly_data_table) 
```

```{r graph_data}
plot_data <- monthly_data %>%
  select(Monat, Stromkosten,Einspeiseverguetung,Einsparung_Eigenverbrauch
  ) %>%
  mutate(
    Stromkosten = -Stromkosten
  ) %>%
  rename(Stromkosten=Stromkosten, Einspeiseverguetung=Einspeiseverguetung,
         `Einsparung(Eigenverbrauch)`=Einsparung_Eigenverbrauch)%>%
  pivot_longer(
    cols = c(Stromkosten, Einspeiseverguetung, `Einsparung(Eigenverbrauch)`),
    names_to = "Category",
    values_to = "Euro"
  )
```


```{r ggplot graph}
ggplot() +
  geom_col(
    data = plot_data,
    aes(x = Monat, y = Euro, fill = Category),
    position = "stack") +
  geom_line(
    data = monthly_data,
    aes(x = Monat, y = Gesamtwirtschaftlichkeit, group = 1, color="GesamtwirtschaftlichkeitP"),linewidth = 1) +
  geom_point(
    data = monthly_data,
    aes(x = Monat, y = Gesamtwirtschaftlichkeit,color="Gesamtwirtschaftlichkeit"),size = 2) +
  labs(
    x = NULL,
    y = "Euro",
    fill = NULL,color=NULL
  ) +
  scale_color_manual(values=c("Gesamtwirtschaftlichkeit"="purple"))+
  theme_minimal()

# WHY ARE THE MONTHS SHOWN IN ENGLISH? HOW DO I CHANGE TO GERMAN?
```

```{r annual data}
annual_data <- pv_data %>%
  summarise(
    `Amortisierung` =
      sum(`Eigenverbrauch [kWh]`) * 0.30 +
      sum(`Netzeinspeisung [kWh]`) * 0.08,
    
    `Durchschnittlicher Netzbezug [kWh]` =
      mean(`Netzbezug [kWh]`),
    
    `Tage mit vollem Speicher [%]` =
      sum(`Speicherung [kWh]` < 0.5) / n() * 100,
    
    `Tage mit ueberdurchschnittlichem Netzbezug [%]` =
      sum(`Netzbezug [kWh]` >
            (mean(`Netzbezug [kWh]`) + sd(`Netzbezug [kWh]`))) / n() * 100
  ) %>%
  mutate(across(where(is.numeric), ~ round(.x, 2)))

knitr::kable(annual_data)
```
```{r pie chart data}
pie_data <- tibble(
  Category = c(
    "Einsparung",
    "Einspeiseverguetung",
    "Restkosten"
  ),
  Price= c(
    sum(pv_data$`Eigenverbrauch [kWh]`) * 0.30,
    sum(pv_data$`Netzeinspeisung [kWh]`) * 0.08,
    12000 - (
      sum(pv_data$`Eigenverbrauch [kWh]`) * 0.30 +
      sum(pv_data$`Netzeinspeisung [kWh]`) * 0.08
    )
  )
)

```

```{r pie chart}
pie_data <- pie_data %>%
  mutate(
    Label = paste0(Category, " = ", round(Price, 2), " €")
  )

ggplot(pie_data, aes(x = "", y = Price, fill = Label)) +
  geom_col(width = 1, color = "white") +
  coord_polar(theta = "y") +
  labs(fill = NULL) +
  theme_void()

#CAN I NOT SHOW THE PRICE ON THE CHART? IT'S KEEP ON OVERLAPPING
```
