---
  title: "Glass Bead Analysis"
  author: "Martin"
  date: "2024-03-15"
  output: md_document
---


```{r setup, echo=FALSE}
# silent load of libraries
suppressMessages(library(tidyverse))

# set working directory to script location
setwd(dirname(rstudioapi::getSourceEditorContext()$path))

```
# Loading and Wrangling data

```{r load_data}
data<-
  read_csv2("Inventory_Glassworkshop.csv", show_col_types = F) |>
  # (1)
  unite( SampleID,Context,Number, sep=".") |>
  relocate(SampleID,.before=Phase)


checkIfValueInVector <- function(x) {
  ifelse(sum(!is.na(x),na.rm=T)>0,1,NA)
}


# extraction of rod data + color annotation
Rods <-
  select(data,
         SampleID,
         starts_with("Rod")) |>
  # correct spelling mistake
  rename(Rod_green = Rod_greeen) |>
  # get color of rod
  pivot_longer(`Rod_yellow`:`Rod_green`, names_to = "color", values_to = "colVal") |>
  drop_na(colVal) |>
  select(-colVal) |>
  mutate(color = str_remove(color,"^.*_") ) |>
  rename_with(~str_replace(., "Rod_", ""))
OGW <-
  select(data,
         SampleID,
         starts_with("OGW")) |>
  # get color of rod
  pivot_longer(-SampleID, names_to = "color", values_to = "colVal") |>
  drop_na(colVal) |>
  select(-colVal) |>
  mutate(color = str_remove(color,"^.*_") )
Pontil <-
  select(data,
         SampleID,
         starts_with("Pontil")) |>
  # get color of rod
  pivot_longer(-SampleID, names_to = "color", values_to = "colVal") |>
  drop_na(colVal) |>
  select(-colVal) |>
  mutate(color = str_remove(color,"^.*_") )

# get type annotation for each piece
typeAnnotation <-
  data |>
  # aggregate rod/ogw/pontil information
  rowwise() |>
  mutate(
    across(matches("^(Rod|OGW|Pontil).+"), as.character),
    Rod = ifelse(sum(!is.na(c_across(matches("^Rod.+"))),na.rm=T)>0,1,NA),
    OGW = ifelse(sum(!is.na(c_across(matches("^OGW.+"))),na.rm=T)>0,1,NA),
    Pontil = ifelse(sum(!is.na(c_across(matches("^Pontil.+"))),na.rm=T)>0,1,NA)
  ) |>
  ungroup() |>
  # drop rod/ogw/pontil data
  select( !matches("^(Rod|OGW|Pontil).+")) |>
  distinct() |>
  # get type
  pivot_longer(cols = -c(Obj,Field,POS,SampleID,Phase), names_to = "type", values_to = "value")|>
  drop_na(value) |>
  select(-value)
  # group_by(SampleID) |>
  # summarize(n=sum(value,na.rm=T)) |>
  # filter(n>1)

# add color information

Beads <-
  read_csv2("GlassBeads.csv", show_col_types = F) |>
  separate(Colour, into = c("Colour","Decor"), sep=",", fill = "right") |>
  mutate(Decor = str_remove(Decor,"^\\s*decor\\s*")) |>
  mutate( SampleID = str_c(Context,".",Number)) |>
  rename(color = Colour)

Beads |> 
  slice_head(n=5) |> 
  knitr::kable()

```

# Color Annotation

```{r color.annotation}

colorAnnotation <-
  typeAnnotation |>
  # rod colors
  left_join(select(Rods, SampleID,color)
            ,by="SampleID") |>
  # ogw colors
  left_join(select(OGW, SampleID,color)
            ,by="SampleID") |>
  # ogw colors
  left_join(select(Pontil, SampleID,color)
            ,by="SampleID") |>
  # bead colors
  left_join(select(Beads, SampleID,color)
            ,by="SampleID") |>
  # join color columns into one
  unite(color,starts_with("color"),sep=", ", na.rm = T) |>
  mutate(color = ifelse(color=="",NA,color)) |>
  mutate(color = ifelse(color=="bluee","blue",color))

# show first rows of color annotation
colorAnnotation |> 
  slice_head(n=10) |> 
  knitr::kable()

```

# Color Histogram

```{r color.histogram}

colorAnnotation |>
  filter(type %in% c("Rod","Bead","OGW")) |>
  ggplot(aes(x=color, fill=color)) +
  geom_bar(stat="count") +
  # set fill colors from data
  scale_fill_manual(values = colorAnnotation$color |> unique() |> str_sort()) +
  facet_wrap(~type
             # , scales = "free"
             ) +
  # rotate x-axis labels
  theme_light() +
  theme(legend.position="none") +
  theme(axis.text.x = element_text(angle = 60, hjust = 1))
```

# Distribution vs. Volume

```{r distribution.volume}
colDat <-
  colorAnnotation |>
  filter(type %in% c("Rod","Bead")) |>
  left_join(select(Beads,SampleID,Dm, Length), by="SampleID") |>
  left_join(select(Rods,SampleID,Dm, Length), by="SampleID") |>
  unite(Dm,starts_with("Dm"),sep=", ", na.rm = T) |>
  unite(Length,starts_with("Length"),sep=", ", na.rm = T) |>
  mutate(across(c(Dm,Length),as.numeric)) |>
  mutate(volume = (Dm^2)*Length*pi) |>
  drop_na(volume)
colDat |>
  ggplot(aes(x=color, y=volume, fill=color)) +
  geom_violin( alpha=0.5)+
  geom_jitter() +
  scale_fill_manual(values = colDat$color |> unique() |> str_sort()) +
  theme(axis.text.x = element_text(angle = 60, hjust = 1)) +
  # disable fill legend
  theme(legend.position="none") +
  scale_y_log10()
```

