---
output: md_document
---
# **Frequency of Depressive Disorder Reports in California**
**Solution for Gulmira's Project from Silin**

******

## Data Manipulation
******
```{r, message = FALSE, warning = FALSE}
library(tidyverse)

dt <- read_csv("../adult-depression.csv")

total_frequency <- dt %>%
  filter(Strata == "Total") %>% 
  select(Year, Total_Frequency = Frequency)

dt_plot <- dt %>%
  left_join(total_frequency, by = "Year") %>%    # combine Total Frequency with the original data
  select(Year, Strata, `Strata Name`, Frequency, Total_Frequency, `Lower 95% CL`, `Upper 95% CL`) %>%
  rowwise() %>%
  mutate(`Annual Frequency` = round(Frequency / Total_Frequency * 100, 2)) %>% # Calculate Annual Frequency
  filter(Strata %in% c("Race-Ethnicity", "Education", "Age")) %>% 
  select(-Total_Frequency) %>% print()
```
## Plotting
******
```{r ggplot, message = FALSE, warning = FALSE}

dt_plot %>% 
  ggplot(aes(x = Year, y = `Annual Frequency`, color = `Strata Name`, group = `Strata Name`)) +
  geom_line() +
  # geom_ribbon(aes(ymin = `Lower 95% CL`, ymax = `Upper 95% CL`), alpha = 0.2) +
  #I assume that the Upper and Lower 95% CL data is not an annual percentage, so it doesn't match the lines drawn by geom_line. And I haven't figured out how that percentage was derived in the original dataframe, so I haven't found out how to calculate the annual data for an Upper and Lower 95% CL either...
  facet_wrap(~Strata, scales = "free_y", ncol = 1) +
  theme_minimal() +
  scale_y_continuous(
    labels = function(x) paste0(x, "%")  # add % to y-axis
  ) +
 labs(
  y = "Annual Frequency (%)", 
  title = "Frequency of Depressive Disorder Reports in California",
  ) +
  theme(
    legend.position = "right",
    legend.title = element_blank(),
    plot.margin = margin(5, 50, 5, 5)
  )
```