---
title: "Nutrient data"
output: md_document
---

# Phase 1 - Drafting a project

The idea of the data project is to extract and process some nutrient data of various food and drinks. I am interested in the composition with respect to macro- and micronutrients. In the end, a sum of nutrients should be represented by several plots showing the distribution of nutrients for the consumed food every day. 

On the same hand, a csv file should be created to store the processed data and consumption information from every day. 

The aim of the project is to work with the data provided, process the data and create a result file that can be used later to show the nutrient composition of your daily meals.

## Data Set

The Swiss Food Composition Database provided by the state of Swizzerland is used for the project. It is a database consisting of over 1000 different food and drinks and the nutrient composition of these.

### Data Preview

```{r display-table, echo=FALSE}
suppressMessages(library(readr))
suppressMessages(library(dplyr))
suppressMessages(library(knitr))

# File name
file = "Schweizer_Nahrwertdatenbank.csv"

# Import file

data <- read_csv(file, col_names = FALSE, show_col_types = FALSE)

#colnames(data) <- data[3,]

data_prev <- data[3:10, c(1, 4, 5,6:8)]
  

# File preview
knitr::kable(head(data[, 1:10], 5), format = "pipe")
```


Entries of the data table are shown for the first ten out of 129 columns.

The complete data set is provided by and available at [The Swiss Food Composition Database](https://view.officeapps.live.com/op/view.aspx?src=https%3A%2F%2Fnaehrwertdaten.ch%2Fwp-content%2Fuploads%2F2023%2F08%2FSchweizer_Nahrwertdatenbank.xlsx&wdOrigin=BROWSELINK).

## Visualisation goals:
The data should be represented as various pie charts and histograms showing the total uptake of micro- and macronutrients with respect to numerous consumed food and drinks. Besides that, the progress in meeting ones daily demand of nutrient should be displayed.   

I want to create a dynamic pie plot that shows the composition of consumed food and drinks with respect to macro- and micronutrients. Ideally, both are represented individually within one pie chart in a manner that at the edge of the circle, the respective progress with respect to the demand is shown. 







