---
title: "Week3sessionex01"
author: "Tobias"
date: "`r Sys.Date()`"
output:
  html_document: default
  pdf_document: default
---

#####################################
* Create an RMD file which
* renders to Markdown output
* uses the current time within the YAML header
* contains a single code chunk that
* loads tidyverse libraries
* uses read_csv() to read the file shown on the following website
*  https://github.com/Dr-Eberle-Zentrum/Data-projects-with-R-and-GitHub/blob/main/Projects/martin-raden/Mammal-comeback-in-Europe-data-OWID-download.csv
* tune the code chunk such that
* the code chunks name is "test.it"
* the code itself is shown, BUT
* no loading information from the tidyverse library is shown
* no loading details from the read_csv() call are shown
* consult https://yihui.org/knitr/options/ for details


```{r label = "test.it", echo = TRUE, message = FALSE, warning = FALSE}
library(tidyverse)
data <- read_csv('/Users/tobiastuchel/Documents/Studium/Fachinhalte/5. Semester GB/R Github/Mammal-comeback-in-Europe-data-OWID-download.csv', show_col_types = F)
```

# Lösungshinweise:

* Datum mit Date: r Sys.Date() im YAML header
* im read_csv Block kann man mit show_col_types = F den Output von read_csv reduzieren
* der Link ist quatsch -> github thema immer erst auf raw gehen und dann dort die URL nehmen
* im Code chunk kann man mit fig.height und width die Breite und größe des outputs bestimmen





