---
title: "natali-mmx"
output: md_document
---

```{r setup, include=FALSE}
library(tidyverse)
# install.packages(c("sf", "rnaturalearth", "rnaturalearthdata", "viridis"))
library(sf)
library(rnaturalearth)
library(rnaturalearthdata)
library(viridis)

```

```{r dataImport, include = FALSE}
data <- read.csv("Salaries_data_scientists.csv")
```

```{r dataManipulation, include = FALSE}
data2024 <- data %>%
  filter(work_year == 2024)
# view(data2024)
```

```{r jobNumbers, include = FALSE}
employeeLocations <- data2024 %>%
  filter(remote_ratio == 100) %>%
  group_by(employee_residence) %>%
  summarise(total_jobs = n()) %>%
  arrange(desc(total_jobs)) %>%
  rename(iso_a2 = employee_residence)
view(employeeLocations)
```

```{r plotJobNumbers}
world <- ne_countries(scale = "medium", returnclass = "sf")
# view(world)

joinedData <- world %>%
  left_join(employeeLocations, by = "iso_a2")

ggplot(data = joinedData) +
  geom_sf(aes(fill = total_jobs), color = "white") +
  scale_fill_viridis(option = "C", na.value = "grey90", name = "Total Jobs") +
  labs(title = "Total Number of Fully Remote Employees by Country)",
       subtitle = "Data Scientists in 2024",
       caption = "Source: Salaries_data_scientists.csv") +
  theme_minimal() +
  theme(legend.position = "bottom")

```
