---
title: "Project - Mobile Device Usage"
output: md_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# General Topic
Mobile devices have become an essential part of our everyday life — being used for communication, information gathering, education, entertainment, and many more. It could even be argued that they have become **too** essential, with people spending many hours looking at their phones. 

There are also many different models of mobile devices on the market with different functions, user-friendliness, and app support.

Consequently, the question arises if there are some models which are so well-designed that their users spend more time with them compared to other models.

# The Dataset
The Dataset *"Mobile Device Usage and User Behavior"* has been published by Vala Khorasani on the data-community platform Kaggle. The dataset consists of only one .csv file with 10 attributes describing the device name, operating system, app usage time, etc. and a total of 700 observations.

The dataset is located [here](https://www.kaggle.com/datasets/valakhorasani/mobile-device-usage-and-user-behavior-dataset). You can find further information about the dataset under the section **Data Card**.

Note: To download the dataset you will have to create a free account on Kaggle. Don't worry you won't receive any spam mail or advertisement. If you still decide that you do not want to create an account I will link the .csv file in my directory where this markdown file is also stored. The directory can be found at </Projects/kickbones1>.

# Manipulation Goals
Luckily, the dataset is pretty straight-forward so there isn't really anything that is not tidy. The only data manipulation you will have to do is summing up the app usage time for every device model.

# Visualization Goals
Try to visualize the data in such a way that it will more or less lead to such a [graph](graph_idea.pdf)

If possible also try to add add the logo of the operating system for every mobile device. It doesn't have to be the exact same image I used, feel free to use something different.