---
title: "Analyzing Soccer Data"
author: "Pleasant Pillai Vijayakumari"
date: "2023-07-22"
output: md_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
```

```{r, echo=FALSE}

#Commit on 22nd

# Load the libraries
suppressPackageStartupMessages(library(ggplot2))
suppressPackageStartupMessages(library(dplyr))
suppressPackageStartupMessages(library(lubridate))
suppressPackageStartupMessages(library(gridExtra))
suppressPackageStartupMessages(library(cowplot))

# Set the working directory to the directory where the CSV file is located
#setwd("C:/Users/Pleasant Pillai/Desktop/R Programming/R2/Advanced-data-processing-with-R/Projects/alexanderwinterstetter")

# Read the CSV file
data <- read.csv("soccer_referee_data.csv")

# Create a new variable "newposition"
data$newposition <- ifelse(data$position == "Goalkeeper", "Goalkeeper",
                           ifelse(data$position == "NA", "NA",
                                  ifelse(data$position %in% c("Center Back", "Left Fullback", "Right Fullback"), "Defense",
                                         ifelse(data$position %in% c("Center Midfielder", "Defensive Midfielder", "Left Midfielder", "Right Midfielder"), "Midfielder", "Offense"))))

# Create a new variable "points" based on victories, ties, and defeats
data$points <- (data$victories * 3) + (data$ties * 1) + (data$defeats * 0)

# Save the updated data frame to a new CSV file
#write.csv(data, "new_soccer_referee_data.csv", row.names = FALSE)

# Find the player with the most victories
player_most_victories <- data$player[which.max(data$victories)]

# Find the player with the most goals
player_most_goals <- data$player[which.max(data$goals)]

# Find the player with the most red cards
player_most_red_cards <- data$player[which.max(data$redCards)]

# Find the newposition with the most victories
newposition_most_victories <- data$newposition[which.max(data$victories)]

# Find the newposition with the most goals
newposition_most_goals <- data$newposition[which.max(data$goals)]

# Find the newposition with the most red cards
newposition_most_red_cards <- data$newposition[which.max(data$redCards)]

# Find the leagueCountry with the most victories
leagueCountry_most_victories <- data$leagueCountry[which.max(data$victories)]

# Find the leagueCountry with the most goals
leagueCountry_most_goals <- data$leagueCountry[which.max(data$goals)]

# Find the leagueCountry with the most red cards
leagueCountry_most_red_cards <- data$leagueCountry[which.max(data$redCards)]

# Find the club with the most victories
club_most_victories <- data$club[which.max(data$victories)]


# Create a data frame for the questions and answers
qa_data <- data.frame(
  Question = c(
    "Player with the most wins",
    "Player with the most goals",
    "Player with the most red cards",
    "",
    "Position with the most wins",
    "Position with the most goals",
    "Position with the most red cards",
    "",
    "League with the most wins",
    "League with the most goals",
    "League with the most red cards",
    "",
    "Club with the most wins"
  ),
  Answer = c(
    player_most_victories,
    player_most_goals,
    player_most_red_cards,
    "",
    newposition_most_victories,
    newposition_most_goals,
    newposition_most_red_cards,
    "",
    leagueCountry_most_victories,
    leagueCountry_most_goals,
    leagueCountry_most_red_cards,
    "",
    club_most_victories
  )
)

# Create the table plot
plot1 <- tableGrob(qa_data, cols = c("Question", "Answer"), rows = NULL,
                   theme = ttheme_minimal(core = list(padding = unit(c(1, 0.4), "mm"))))

# Create a bar plot of points per club, grouped by leagueCountry
plot2 <- ggplot(data, aes(x = club, y = points, fill = leagueCountry)) +
  geom_bar(stat = "identity", position = position_dodge(width = 0.8)) +
  labs(x = "Club", y = "Points", fill = "League") +
  ggtitle("Points per Club by League") +
  theme_minimal() +
  theme(axis.text.x = element_text(angle = 55, hjust = 1),
        text = element_text(size = 7))
  
# Create a bar plot of points per club, grouped by leagueCountry
# plot2 <- ggplot(data, aes(x = club, y = points, fill = leagueCountry)) +
#   geom_bar(stat = "identity", position = position_dodge(width = 0.8)) +
#   labs(x = "Club", y = "Points", fill = "League") +
#   ggtitle("Points per Club by League") +
#   theme_minimal() +
#   theme(axis.text.x = element_text(angle = 55, hjust = 1),
#         strip.text = element_text(size = 8, hjust = 0.5, vjust = 0.5)) +
#   facet_wrap(~ leagueCountry, ncol = 1, scales = "free_x")

# Convert the "birthday" column to a Date format
data$birthday <- as.Date(data$birthday, format = "%d.%m.%Y")

# Calculate the age of the players based on the "birthday" column
data$age <- floor(time_length(interval(data$birthday, Sys.Date()), "years"))

# Create a histogram of player ages by league with different colors
plot3 <- ggplot(data, aes(x = age, fill = leagueCountry)) +
  geom_histogram(binwidth = 1, color = "black") +
  labs(x = "Age", y = "Count") +
  ggtitle("Distribution of Player Ages per League") +
  theme_minimal() +
  theme(axis.text.x = element_text(angle = 45, hjust = 1),
        text = element_text(size = 7)) +  # Adjust the text size here
  facet_grid(. ~ leagueCountry)

# Calculate the ratio of red cards to yellow cards per league
ratio_data <- aggregate(cbind(redCards, yellowCards) ~ leagueCountry, data, sum)
ratio_data$red_yellow_ratio <- ratio_data$redCards / ratio_data$yellowCards

# Create a scatter plot
plot4 <- ggplot(ratio_data, aes(x = leagueCountry, y = red_yellow_ratio)) +
  geom_point(size = 3, color = "blue") +
  labs(x = "League", y = "Red/Yellow Card Ratio") +
  ggtitle("Ratio of Red Cards to Yellow Cards per League") +
  theme_minimal() +
  theme(text = element_text(size = 7))

# Arrange plots vertically
plot_arranged <- plot_grid(plot1, plot2, plot3, plot4, ncol = 1)

# Display the arranged plots
plot_arranged

```
