---
title: "My initial solution to Bernhard's project"
output:
  html_notebook:
    code_folding: hide
date: 15/01/23
---
### The original data
```{r} 
knitr::opts_chunk$set(warning = FALSE, message = FALSE)
library(tidyverse)
library(scales)

data <- read_csv2("nmin_jena_2022.csv", show_col_types = FALSE)
data
```

The data is modified by selecting the relevant columns and introducing groups as suggested in the project description.
```{r setup, include=FALSE} 
knitr::opts_chunk$set(warning = FALSE, message = FALSE)
data %>%
  select("Nmin [mg/kg]", "sowndiv", "numleg") %>%
  rename(Nmin=`Nmin [mg/kg]`) %>% 
  mutate(sowndiv_factor=factor(sowndiv),
         numleg_factor=factor(numleg)) %>%
  mutate(rec_sowndiv=fct_recode(sowndiv_factor, "0-1"="0", "0-1"="1", "2-4"="2","2-4"="4","8-16"="8", "8-16"="16","60"="60"),
         rec_numleg=fct_recode(numleg_factor, "0-1"="0","0-1"="1","2-3"="2","2-3"="3","4-5"="4","4-5"="5", "6-8"="6","6-8"="7","6-8"="8", "12"="12")) %>%
  group_by(rec_sowndiv,rec_numleg) %>%
  mutate(Nmin_mean=mean(Nmin, na.rm = T),
         sd=sd(Nmin, na.rm=T)) -> mod_data
```
## The plot
Unfortunately, the error bars are ruining the plot so far... 
```{r}
ggplot(mod_data, aes(x=rec_numleg, y=Nmin_mean, fill=rec_sowndiv)) + 
  geom_bar(stat = "identity", position = "dodge")+
  ylab(expression(N[min]* " [mg/kg]"))+
  xlab("Number of legumes")+
  labs(title = str_wrap("The Jena project", 100), fill=str_wrap("Diversity level"))+
  theme(panel.background = element_rect(fill='black', colour='black'),
        axis.text = element_text(colour = "white"),
        axis.title.x = element_text(colour = "white"),
        axis.title.y = element_text(colour = "white"),
        plot.background = element_rect(fill='black'),
        plot.title = element_text(color = "white"),
        legend.background = element_rect(fill = "black", colour = "white"),
        legend.text=element_text(color="white"),
        legend.title = element_text(colour = "white"))+
  expand_limits(x = c(0, NA), y = c(0, NA)) +
  scale_y_continuous(labels = unit_format(unit = "Mio", scale = 1e-6, big.mark = ".", decimal.mark = ","))+
  geom_errorbar(aes(ymin=Nmin-sd, ymax=Nmin+sd), width=.2,
                 position=position_dodge(.9), na.rm = T) 

```


