---
title: "Joschka8878"
author: "Joschka Christ"
date: "2024-06-10"
output: md_document
---

```{r setup, include=FALSE}
library(dplyr)
library(lubridate)
library(ggplot2)
library(reshape2)
unzip("Projects/DrMohamedElsherif/BikeData.zip", exdir = "BikeData")
Bike_Count <- read.csv("BikeData/bike_counts.csv")
Counter_Sites <- read.csv("BikeData/counter_sites.csv")
Holidays <- read.csv("BikeData/holidays.csv")
Weather <- read.csv("BikeData/weather.csv")

bike_counts_agg <- Bike_Count %>%
  group_by(time, counter_site_id) %>%
  summarise(bike_count_agg = sum(bike_count))
merged <- merge(bike_counts_agg, Bike_Count, by = c("time", "counter_site_id"), all.x = T)
merged <- merge(merged, Counter_Sites, by = "counter_site_id", all.x = T)
merged$date <- as.Date(merged$time)
merged <- merge(merged, Holidays, by = "date", all.x = T)
merged[is.na(merged)] <- 0
merged <- merged %>% select(-"date")
merged <- merge(merged, Weather, by = "time")
merged$week <- week(merged$time)
bike_count_week <- aggregate(bike_count ~ week, merged, FUN = sum)
merged$hour <- hour(merged$time)
merged$wday <- wday(merged$time)
bike_count_wday <- merged %>% 
  group_by(hour, wday) %>%
  summarize(avg_count = mean(bike_count))
```

## Data Visualization 1

```{r}
merged$counter_site_id <- factor(merged$counter_site_id)
custom_colors <- c("100003358" = "blue", "100003359" = "purple", "100026408" = "red")
Graph1 <- ggplot(merged, aes(x = time, y = bike_count, color = counter_site_id)) +
  geom_line() +
  scale_color_manual(values = custom_colors) +
  labs(x = "Time", y = "Bike Count", title = "Bike Counts for Each Counter Site over Time") +
  theme_minimal()
print(Graph1)
```

## Data Visualization 2

```{r}
Graph2 <- ggplot(merged, aes(x = week, y = bike_count, color = counter_site_id)) +
  geom_line() +
  facet_wrap(~ counter_site_id, nrow = 3) +
  scale_color_manual(values = custom_colors) +
  labs(x = "Week", y = "Total Bike Count", title = "Number of Bikes per Week for Each Counter Site") +
  theme_minimal()
print(Graph2)
```

## Data Visualization 3

```{r}
weekdays <- c("Monday", "Tuesday", "Wednesday", "Thursday", "Friday", "Saturday", "Sunday")
bike_count_wday$wday <- factor(bike_count_wday$wday, labels = weekdays)
  heatmap_data <- dcast(bike_count_wday, hour ~ wday, value.var = "avg_count")
  heatmap_data_long <- melt(heatmap_data, id.vars = "hour", variable.name = "weekday", value.name = "average_bike_count")
Heatmap <- ggplot(heatmap_data_long, aes(x = weekday, y = hour, fill = average_bike_count)) +
  geom_tile() +
  scale_fill_gradient(low = "white", high = "steelblue") +
  labs(x = "Weekday", y = "Hour", title = "Average Bike Count Timetable Heatmap") +
  theme_minimal() +
  theme(axis.text.x = element_text(angle = 90, hjust = 1))
print(Heatmap)

```
