---
title: "SamiPhoenix"
output: md_document
---

```{r libraries, echo=FALSE, message=FALSE}

library(tidyverse)
library(kableExtra)

```

This project investigates young peoples' behavior when it comes to getting information on health topics online.
The data set is based on a questionnaire that notes how old the participants are, what sex, and how they get their information on health.

```{r everything, echo=TRUE, message=FALSE, warning=FALSE}

phone_ownership <- function(table){
  case_when(
    table$`Do you have a mobile phone?` == "No" ~ 0,
    table$`Is this mobile phone yours or do you share it ?` == "Shared" ~ 1,
    TRUE ~ 2
  )
}


  # Reading Data
data <-
  read_delim("2024-12-09_FALAH_Vanuatu_socialMediaUse_Zenodo_anonymized.csv",
             delim = ";",
             locale = locale(encoding = "Windows-1252")) %>% 
  
  # 1. Removing Columns with Text Answers:
  select(
    -`Which social media platform/site (Facebook, Instagram, Twitter, Tiktok, Snapchat) is your favourite to use for your health? And what do you like about it?`,
    -`For searching health information, which app, social media or website do you use ?`,
    -`For discussing health topics with other people online, which app, social media or website do you use ?`
  ) %>% 
  
  # 2. Merging Phone Ownership Columns:
  mutate(`mobile_phone ownership` = phone_ownership(.)) %>% 
  select(-`Do you have a mobile phone?`, -`Is this mobile phone yours or do you share it ?`) %>% 
  
  # 3. Simplifying Participant's Answers:
  mutate_all(funs(str_replace_all(., "Checked", "1"))) %>%
  mutate_all(funs(str_replace_all(., "Unchecked", "0"))) %>%
  mutate_all(funs(str_replace_all(., "Yes", "1"))) %>%
  mutate_all(funs(str_replace_all(., "No", "0"))) %>%
  
  # Handling NA:
  replace(is.na(.), "0") %>%
  
  # Simplifying Age
  mutate(`Age range` = case_when(
    str_detect(`Age range`, "Greater than or equal to 18") ~ ">= 18",
    str_detect(`Age range`, "Between 16 and 17 inclusive") ~ "16-17",
    str_detect(`Age range`, "Lower than or equal 15")      ~ "<= 15"
  )) %>% 
  mutate(Age_Sex = paste(`Age range`, Sex)) %>%
  
  
  
  
  
  
  # 2. Merging again
  mutate(Health_Platform = case_when(
    `Favourite platform/site for health: social media`  == 1 ~ "social media",
    `Favourite platform/site for health: search engine` == 1 ~ "search engine",
    `Favourite platform/site for health: unclear`       == 1 ~ "unclear",
    `Favourite platform/site for health: none`          == 1 ~ "none"
  )) %>%
  
  
# sowas macht man eigentlich mit einem
# 
# pivot_longer() %>% # aus spalten label und 01NA werte machen
# drop_na() oder filter==1 %>% # auf 1er werte reduzieren
# select(-wertspalte) %>% # weil nur noch 1er brauchen wir die spalte nicht mehr
# mutate(str_remove(.., prefix)) # prefix der spaltennamen entfernen, sodass die gewünschten tags übrig bleiben
# und weil der ansatz generisch ist, kannst den
# 
# in eine funktion packen (mit table und prefix als argument)
# mit dem prefix steuerst du das pivot
# und den reduzierten table gibst zurück
# meinst das kannst mal versuchen? wär cool! 😎
  
  # pivot_longer(
  #   cols = `Favourite platform/site for health: social media`:`Favourite platform/site for health: none`,
  #   names_to = "Health_Platform",
  #   values_to = "Health_Usage"
  # ) %>% 
  # filter(Health_Usage == 1) %>%
  # select(-Health_Usage) #%>%
  # 
  # 
  
  
  
  mutate(HISB_Platform = case_when(
    `For searching health information: social media`    == 1 ~ "social media",
    `For searching health information: search engine`   == 1 ~ "search engine",
    `For searching health information: web site`        == 1 ~ "web site",
    `For searching health information: unclear`         == 1 ~ "unclear",
    `For searching health information: none`            == 1 ~ "none"
  )) %>% 
  mutate(Discussion_Platform = case_when(
    `For discussing: social media` == 1 ~ "social media",
    `For discussing: search engine` == 1 ~ "search engine",
    `For discussing: app` == 1 ~ "app",
    `For discussing: web site` == 1 ~ "web site",
    `For discussing: unclear` == 1 ~ "unclear",
    `For discussing: none` == 1 ~ "none"
  )) %>% 
  mutate(across(
    c(
      Health_Platform,
      HISB_Platform,
      Discussion_Platform
    ),
    ~ ifelse(
      `Do you use apps, social media or websites for your health?` == 0,
      "none",
      .
    )
  )) %>% 
  
  # 4. Renaming and combining
  rename(
    Age = `Age range`,
    Computer_Browsing =
      `When you are on the computer and/or tablet, what type of actions do you most often perform?   (choice=Searching for general information)`,
    Computer_Studying =
      `When you are on the computer and/or tablet, what type of actions do you most often perform?   (choice=Study or homeworks)`,
    Computer_Other =
      `When you are on the computer and/or tablet, what type of actions do you most often perform?   (choice=Other)`,
    Phone_Browsing =
      `When you are on your mobile phone, what type of actions do you perform most often?   (choice=Searching for general information)`,
    Phone_Studying =
      `When you are on your mobile phone, what type of actions do you perform most often?   (choice=Study or homeworks)`,
    Phone_Other =
      `When you are on your mobile phone, what type of actions do you perform most often?   (choice=Other)`
  ) %>% 
  mutate(Computer_Socializing = (
    as.numeric(`When you are on your mobile phone, what type of actions do you perform most often?   (choice=Discussion by email or on the digital social networks with friends or family)`)
    + as.numeric(`When you are on your mobile phone, what type of actions do you perform most often?   (choice=Watching your social network feed)`)
  )) %>% 
  mutate(Computer_Entertainment = (
    as.numeric(`When you are on your mobile phone, what type of actions do you perform most often?   (choice=Listening to the music)`) +
      as.numeric(`When you are on your mobile phone, what type of actions do you perform most often?   (choice=Playing games)`) +
      as.numeric(`When you are on your mobile phone, what type of actions do you perform most often?   (choice=Viewing videos)`)
  )) %>% 
  mutate(Phone_Socializing = (
    as.numeric(`When you are on your mobile phone, what type of actions do you perform most often?   (choice=Discussion by email or on the digital social networks with friends or family)`) +
      as.numeric(`When you are on your mobile phone, what type of actions do you perform most often?   (choice=Watching your social network feed)`) +
      as.numeric(`When you are on your mobile phone, what type of actions do you perform most often?   (choice=Telephone conversation)`)
  )) %>% 
  mutate(Phone_Entertainment = (
    as.numeric(`When you are on your mobile phone, what type of actions do you perform most often?   (choice=Listening to the music)`) +
      as.numeric(`When you are on your mobile phone, what type of actions do you perform most often?   (choice=Playing games)`) +
      as.numeric(`When you are on your mobile phone, what type of actions do you perform most often?   (choice=Viewing videos)`)
  )) %>% 
  mutate(HISB_Usage = (
    as.numeric(`For searching health information: social media`) +
    as.numeric(`For searching health information: search engine`) +
    as.numeric(`For searching health information: web site`)
  )) %>% 
  select(
    -(`Favourite platform/site for health: social media`:`For discussing: none`)
  ) %>%
  select(
    -starts_with("When"),
    -`Do you use apps, social media or websites for your health?`
  ) %>% 
  
  # Prep for Visualization
  # Drop NA in Age
  
  drop_na(Age) %>%
  mutate(Age_Sex = as.factor(Age_Sex))
  

  
# print with kable
data |> 
  slice_head(n=10) |> 
  kableExtra::kable(format = "markdown", caption = "Cleaned Data for Analysis") 
  



```

```{r Vis, echo=TRUE, message=FALSE}

group_order <- c("<= 15 F", "<= 15 M", "16-17 F", "16-17 M", ">= 18 F", ">= 18 M")
data$Age_Sex <- factor(data$Age_Sex, levels = group_order)

HISB_Grouped <- data %>%
  mutate(HISB_indicator = as.integer(HISB_Usage > 0)) %>%
  group_by(Age_Sex) %>%
  summarise(HISB_Usage = mean(HISB_indicator, na.rm = TRUE), .groups = "drop")

data <- data %>%
  mutate(across(Computer_Browsing:`mobile_phone ownership`, as.numeric))

Summary_Computer <- data %>%
  group_by(Age_Sex) %>%
  summarise(
    Searching     = mean(Computer_Browsing),
    Socializing   = mean(Computer_Socializing),
    Entertainment = mean(Computer_Entertainment),
    Studying      = mean(Computer_Studying),
    Others        = mean(Computer_Other),
    .groups = "drop"
  )

Sum_Computer <- Summary_Computer %>%
  mutate(
    total = Searching + Socializing + Entertainment + Studying + Others,
    Searching = Searching / total,
    Socializing = Socializing / total,
    Entertainment = Entertainment / total,
    Studying = Studying / total,
    Others = Others / total
  ) %>%
  select(-total)


Summary_Phone <- data %>%
  group_by(Age_Sex) %>%
  summarise(
    Searching     = mean(Phone_Browsing),
    Socializing   = mean(Phone_Socializing),
    Entertainment = mean(Phone_Entertainment),
    Studying      = mean(Phone_Studying),
    Others        = mean(Phone_Other),
    .groups = "drop"
  )

Sum_Phone <- Summary_Phone %>%
  mutate(
    total = Searching + Socializing + Entertainment + Studying + Others,
    Searching = Searching / total,
    Socializing = Socializing / total,
    Entertainment = Entertainment / total,
    Studying = Studying / total,
    Others = Others / total
  ) %>%
  select(-total)

data_plotting <- list(
  "Computer Usage" = Sum_Computer,
  "Mobile Phone Usage" = Sum_Phone
) %>% 
  bind_rows(.id = "Device") %>%
  pivot_longer(
  Searching:Others,
  names_to = "Usage",
  values_to = "Proportion"
  ) %>% 
  mutate(
    Usage = factor(Usage, levels = c("Searching", "Socializing", "Entertainment", "Studying", "Others")),
    Device = factor(Device, levels = c("Computer Usage", "Mobile Phone Usage"))
    )


HISB_data <- bind_rows(
  HISB_Grouped %>% mutate(Device = "Computer Usage"),
  HISB_Grouped %>% mutate(Device = "Mobile Phone Usage")
) %>%
  mutate(Device = factor(Device, levels = c("Computer Usage", "Mobile Phone Usage")))

usage_colors <- c(
  Searching = "#1B9E77",
  Socializing = "#D95F02",
  Entertainment = "#7570B3",
  Studying = "#E7298A",
  Others = "#66A61E"
)
# Visualization begins:

ggplot(data_plotting, aes(x = Age_Sex, y = Proportion, fill = Usage)) +
  geom_col() +
  geom_line(data = HISB_data, aes(x = Age_Sex, y = HISB_Usage, group = 1),
            inherit.aes = FALSE, color = "black", linewidth = 1) +
  geom_point(data = HISB_data, aes(x = Age_Sex, y = HISB_Usage),
            inherit.aes = FALSE, color = "black", size = 2) +
  facet_wrap(~Device, nrow = 1) +
  scale_fill_manual(
    values = usage_colors
  ) +
  scale_y_continuous(
    name = "Proportion of Participants",
    labels = function(x) sprintf("%.1f", x),
    expand = c(0, 0),
    sec.axis = sec_axis(
      transform = ~.,
      name = "HISB Rate", 
      labels = function(x) sprintf("%.1f", x)
      )
    )


# The values are not right, but I don't have what it takes to troubleshoot my code :/
  

```


