
Dana Jabari
R2 course

Name of the data set: cloze_task_results.csv

----

Hi!

Thank you for looking at my project. 
During a psychology course of mine, we have conducted an an pre-experiment, in which
we collected "best" alternatives for different key words. I am wondering if there is
a neat way to present the best alternatives for each key word.


The file is named "cloze_task_results.csv". You will find that dataset in my 
folder on github. 

Our participants were supposed to continue sentences, which were presented to 
them on their laptop screen. 

For example (it was in german):

"Das ist kein Auto, sondern ..."

The number of alternatives to the sentences, given by the participants were collected.

Explanation of the variables:

text:     "Das is kein Auto, sondern"
response: "Fahrrad" (Fahrrad is an example)
count:    number of times a certain response was typed in

```{r}
data <- read.csv("cloze_task_results.csv")
head(data)
```


My project for you would be:

- tidy the data
- find out, which word turned out to be the best alternative for the different 
  "key words". 
  Example: for the key word "Aldi" the best alternative is "lidl"
- Make a suitable plot for the different key words on the x-axis, and on the
  y-axis should be the "best alternatives" for each key word, marked with the 
  count of each best alternative.
- for clarification: the "best alternative" is the alternative word, which
  is named the most for each key word

I do not have a concrete vision for a plot, just create one which you think makes
sense in this context. I trust you with this decision!

Thank you for your interest!
If you have any questions, do not hesititate to ask me. 

Best,
Dana


