---
title: "My initial solution to Dana´s project"
output: html_notebook
date: "19/12/22"
---

# Processing the data
```{r}
library(tidyverse)
data <- read_csv("cloze_task_results.csv", show_col_types = FALSE)
data %>%
  group_by(text)%>%
  summarise(
    key_word=text,
    response=response,
    sum_count = sum(count),
    count = count
  )%>%
filter(count==max(count, na.rm = T))%>%
mutate(prop_top_answ=count/sum_count)%>%
ungroup()%>%
  separate(col=key_word, into = c("text1", "text2"), sep = "\\bist|sind\\b\\s+", remove = TRUE)%>%
  select(-c(text, text1))%>%
  separate(col=text2, into = c("key_word", "text"), sep = ", sondern", remove = TRUE)%>%
  select(-text) -> mod_data

mod_data$count_groups <- cut2(mod_data$count,g=34)
mod_data$count_groups <-factor(mod_data$count_groups, levels = rev(levels(mod_data$count_groups)))
```

# Visualising the data
```{r}
mod_data %>%
  filter(count>15 & count<=20)%>%
  mutate(key_w=fct_reorder(key_word, count),
         lab_loc=count+10) -> plot_mod_data
the_title = str_c("Top responses with count > ",min(plot_mod_data$count, na.rm = T), " & count <= ",max(plot_mod_data$count, na.rm = T))
ggplot(plot_mod_data, aes(x=key_w,y=count, fill=count_groups))+
  geom_col()+
  labs(title = str_wrap(the_title, 50), fill=str_wrap("Count (grouped)"))+
  ylim(0, 50)+
  #facet_wrap(vars(count_groups), scales = "free")+
  coord_flip()+
  xlab("") +
  scale_fill_discrete() +
  ylab("Count")+
  geom_text(aes(x=key_w, y=lab_loc, label=str_c("sondern ", response)))+
  theme_gray()+
  theme(plot.title = element_text(hjust = 0.5))
```

  

  
  
  


  
```



