---
title: "Projekt von Dana"
author: "Eric Offermann"
date: '2022-12-19'
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# Lösung von Danas Projekt


```{r, echo = FALSE, message=FALSE, warning=FALSE}
library(tidyverse)
library(ggplot2)
setwd("D:/Eric/Documents/Uni_Tuebingen_Kurse/5. Semester/Kurs R2/Aufgabe_1/Advanced-data-processing-with-R/Projects/dana-jabari/")


data <- read.csv("cloze_task_results.csv") %>%
  rename(
    Frage = 1,
    Antwort = 2,
    Faelle = 3
  ) %>%
  mutate(Schlagwort = str_extract(Frage, "\\S+(?=,)"))


```

## Aufgabe

```{r hallo, echo=FALSE,message=FALSE, warning=FALSE}
data %>%
  distinct(Schlagwort, .keep_all = T) %>%
  slice_max(Faelle, n = 20) %>%
  #str_extract(Frage, "\S+(?=,)") %>%
  ggplot(aes(fill = as.factor(Antwort), x = Faelle, y = reorder(Schlagwort, -Faelle))) +
  geom_bar(position = "stack", stat = "identity")+
  geom_text(aes(label=str_to_title(Antwort)), x = 2, vjust= 0.15, size = 3, nudge_y = -0.1)+
  labs(x = "Fälle",
       y = "Frage: Dort ist kein(e) ***, sondern ein..",
       fill = "Fälle")+ 
  ggtitle("Die häufigsten Antworten auf folgende Fragen")+
  #scale_y_continuous(labels = comma)+
  theme(legend.position="none")

```