---
title: "emily-works"
output: md_document
---

```{r setup, include=FALSE}
library(tidyverse)
library(ggplot2)
library(readr)
```

# Data Import
```{r data-import, message = FALSE}
raw_data  <- read_csv("dependencies/SpeciesByKingdomAndClass.csv")
```

## Add Kingdom Data
```{r add-kingdom}

kingdoms <- c("Animalia", "Chromista", "Fungi", "Plantae") # list kingdoms in the order they appear in

kingdom_data  <- raw_data %>%
  mutate(
    ClassChange = Name < lag(Name),     # create column that says TRUE when a change appears (new kingdom)
    ClassChange = replace_na(ClassChange, TRUE),       # replaces NA in 1st observation with TRUE
    AllKingdom = ifelse(ClassChange == TRUE, kingdoms[cumsum(ClassChange)], NA)
  ) %>%
  fill(AllKingdom, .direction = "down") %>%      # fills the NAs with the value
  mutate(
    Kingdom = if_else(Name == "Total", NA, AllKingdom)
    ) %>%
  select(!c("ClassChange","AllKingdom"))     # removes the ClassChange & AllKingdom column 

```    


# Data Manipulation
```{r data-manipulation}

manipulated_data <- kingdom_data %>%
  select(!("CR(PE)":"Subtotal (EX+EW+ CR(PE)+CR(PEW))")) %>%  # removes columns
  rowwise() %>%
  mutate( 
    NearThreatened = sum(c_across("LR/cd":"NT or LR/nt"))  # combines columns
        ) %>%
  select(!("LR/cd":"NT or LR/nt")   # removes columns
         ) %>%
  rename(
    "Extinct" = "EX",
    "ExtinctWild" = "EW",
    "CriticallyEndangered" = "CR",
    "Endangered" = "EN",
    "Vulnerable" = "VU",
    "LowRisk" = "LC or LR/lc",
    "DataDeficient" = "DD"
    ) %>%
  select(`Name`,`Kingdom`,`Extinct`:`Subtotal (threatened spp.)`, `NearThreatened`, `LowRisk`:`Total`)     # changes column order

```

# Data Visualization

First step: create a new seperate table
```{r data-visualization}

data_table_filtered <- manipulated_data %>%
  filter ( Total > 1000 ) %>%
  transmute(
    `Name`,
    `Kingdom`,
    across(c(`Extinct`:`Total`), ~round ( .x / Total * 100, 2), .names = "{.col} [%]")
    )

```

Create Barplot 1:
```{r barplot-1}

data_table_filtered %>%
  rowwise() %>%
  mutate(
    `Unaffected [%]` = sum(c_across(`NearThreatened [%]`:`DataDeficient [%]`))
  ) %>%
  group_by(Kingdom) %>%
  summarise(
    Extinct = mean(`Subtotal (EX+EW) [%]`),
    Affected = mean(`Subtotal (threatened spp.) [%]`),
    Unaffected = mean(`Unaffected [%]`)
  ) %>%
  pivot_longer(
    cols = c(Extinct, Affected, Unaffected),
    names_to = "Category",
    values_to = "Percentage"
  ) %>%
  filter(!is.na(Kingdom)) %>%
  ggplot() +
   geom_bar(aes( x = Kingdom, y = Percentage, fill = Category), stat = "identity", position = "stack") +
  ggtitle("Distribution of Impact Among Kingdoms") +
  xlab("Kingdom") +
  ylab("Average Percentage within Species") +
  scale_fill_manual(values = c("Extinct" = "red", "Affected" = "orange", "Unaffected" = "green"))

```

Create Barplot 2:

First step, prepare the data:
```{r barplot-2-data-preparation}

library(dplyr)

data_table_unfiltered <- manipulated_data %>%
  transmute(
    `Name`,
    `Kingdom`,
    across(c(`Extinct`:`Total`), ~round ( .x / Total * 100, 2), .names = "{.col} [%]")
    ) %>%
  rowwise() %>%
  mutate(
    `Affected [%]` = sum(c_across(`Extinct [%]`:`CriticallyEndangered [%]`))
  ) 

data_top_ten <- data_table_unfiltered %>%
  ungroup() %>%
  arrange(desc(`Affected [%]`)) %>% 
  slice_head(n = 10)

data_bottom_ten <- data_table_unfiltered %>%
  ungroup() %>%
  arrange(desc(`Affected [%]`)) %>% 
  slice_tail(n = 10)

gap_plot <- tibble(
  `Name` = "...",
  `Kingdom` = NA_character_,
  `Affected [%]` = NA_real_
)
  
ordered_data <- bind_rows(
  data_top_ten %>% select(`Name`, `Kingdom`, `Affected [%]`),
  gap_plot,
  data_bottom_ten %>% select(`Name`, `Kingdom`, `Affected [%]`)
)

ordered_levels <- c(as.character(data_top_ten$Name), "...", as.character(data_bottom_ten$Name))
ordered_data$Name <- factor(as.character(ordered_data$Name), levels = ordered_levels)

```

Now we map this to get the desired plot:
```{r barplot-2-mapping}

ordered_data %>%
  ggplot() +
  geom_col(aes(x = Name, y = `Affected [%]`, fill = Kingdom)) +
  theme_minimal() +
  theme(axis.text.x = element_text(angle = 90, vjust = 0.5, hjust = 1))


```

