---
title: "Nutriscore Frequency Plotting"
author: "Pleasant Pillai Vijayakumari"
date: "2023-07-18"
output: md_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
```

```{r, echo=FALSE, warning=FALSE}

# Load the libraries
suppressPackageStartupMessages(library(ggplot2))
suppressPackageStartupMessages(library(readr))

# Read the data from Food_data_0.txt
data <- read_delim("Food_data_0.txt", delim = "\t", col_names = TRUE, col_types = cols(), show_col_types = FALSE)

# Filter the subset based on conditions
subset_data <- subset(data, !(brands == "Nestle" & grepl("palm oil", ingredients_text, ignore.case = TRUE)))

# Filter out rows where nutriscore_score is 0
filtered_data_1 <- subset(subset_data, nutriscore_score != 0)

# Define the colors for nutriscore_grade
Nutri_Colors <- c("#058b49", "#74c928", "#fbc801", "#f4730e", "#ef2d1a")

# Plot histogram of nutriscore_score with colors based on nutriscore_grade
ggplot(filtered_data_1, aes(x = nutriscore_score, fill = toupper(nutriscore_grade))) +
  geom_histogram(binwidth = 0.5, position = "identity", alpha = 1) +
  scale_fill_manual(values = Nutri_Colors) +
  labs(x = "Nutriscore Score", y = "Frequency", fill = "Nutriscore Grade") +
  theme_minimal()

# Filter out rows with "unknown" pnns_groups_1 and nutriscore_score equal to 0
# filtered_data_2 <- data |>
#     filter(pnns_groups_1 != "unknown" & as.numeric(nutriscore_score) != 0)
# 
# # Group the data by pnns_groups_1 and calculate the average nutriscore
# grouped_data <- filtered_data_2 |>
#   group_by(pnns_groups_1) |>
#   summarize(average_nutriscore = mean(nutriscore_score))
# 
# # Sort the data by average_nutriscore in ascending order
# grouped_data <- grouped_data[order(grouped_data$average_nutriscore), ]

# Define the nutriscore colors
nutriscore_colors <- c("#058b49", "#74c928", "#fbc801", "#f4730e", "#ef2d1a")

# Plot the average nutriscore for each group
# ggplot(data = grouped_data, aes(x = pnns_groups_1, y = average_nutriscore, fill = average_nutriscore)) +
#   geom_bar(stat = "identity", width = 0.7) +
#   scale_fill_gradientn(colors = nutriscore_colors, na.value = "white") +
#   labs(x = "Food Group", y = "Average Nutri-Score") +
#   theme_minimal()




```

