---
title: "Davidprntz"
author: "David Prießnitz"
date: "`r Sys.Date()`"
output: md_document
---

```{r}
library(tidyverse)
library(readxl)
survey <- read_excel('/Users/dave/Downloads/Elise.xlsx')
```

```{r}
survey_clean <- survey %>% 
  filter(grepl("^ASMR021_", Subject)) %>% # Filter rows that start with "ASMR021_"
  mutate(Subject = as.integer(gsub("ASMR021_", "", Subject))) %>%  # Extract just the number part
  select(-Sex) %>%  # Remove the Sex column
  drop_na() %>% # Remove rows with any missing data
 mutate(SSPDT_R = 100-SSPDT) %>%
 mutate(SSPSDT_R = 100-SSPSDT)
```

```{r}
library(dplyr)

survey_avg <- survey_clean %>%
  select(Subject, starts_with("ssp")) 
 Average <- colMeans(survey_avg)
```


```{r}
#Calculating 3 personality factor scores 

survey_clean <- survey_clean %>% 
  mutate(Neuroticism_related_traits = rowMeans(select(., SSPSTAT, SSPPSTAT, SSPSST,SSPLAT,SSPET,SSPMT), na.rm = TRUE)) %>%
  mutate(Aggressiveness = rowMeans(select(., SSPTIT, SSPVTAT, SSPPHTAT,SSPSDT_R), na.rm = TRUE)) %>% 
  mutate(Extraversion = rowMeans(select(., SSPIT, SSPAST, SSPDT_R), na.rm = TRUE))  
```


```{r}
#Data Visualization Goals violin plots
survey_clean_PT <- survey_clean %>% select(-c(1:113))
survey_clean_long <- survey_clean_PT %>% 
  pivot_longer(
    cols = everything(), 
    names_to = "personality_traits", 
    values_to = "Value"
  )

# Create a vector with the desired order of personality traits
rank <- c("Neuroticism_related_traits", "SSPSTAT", "SSPPSTAT", "SSPSST","SSPLAT","SSPET","SSPMT", 
                      "Aggressiveness", "SSPTIT", "SSPVTAT", "SSPPHTAT","SSPSDT", 
                      "Extraversion", "SSPIT", "SSPAST", "SSPDT")
survey_clean_long$personality_traits <- factor(survey_clean_long$personality_traits, levels = rank)
```

```{r}
colors <- c("Neuroticism_related_traits" = "skyblue3", 
            "SSPSTAT" = "skyblue1", 
            "SSPPSTAT" = "skyblue1", 
            "SSPSST" = "skyblue1",
            "SSPLAT" = "skyblue1",
            "SSPET" = "skyblue1",
            "SSPMT" = "skyblue1",
             "Aggressiveness"= "red3",
             "SSPTIT" = "tomato1", 
             "SSPVTAT" = "tomato1", 
             "SSPPHTAT" = "tomato1",
             "SSPSDT" = "tomato1", 
               "Extraversion"= "springgreen4", 
               "SSPIT" = "springgreen3", 
               "SSPAST" = "springgreen3", 
               "SSPDT" = "springgreen3")
rank <- c("Neuroticism_related_traits", "SSPSTAT", "SSPPSTAT", "SSPSST","SSPLAT","SSPET","SSPMT", 
                      "Aggressiveness", "SSPTIT", "SSPVTAT", "SSPPHTAT","SSPSDT", 
                      "Extraversion", "SSPIT", "SSPAST", "SSPDT")
survey_clean_long$personality_traits <- factor(survey_clean_long$personality_traits, levels = rank)
```

```{r, echo=FALSE, fig.width=20, fig.height=10}
violin_plot <- ggplot(survey_clean_long, aes(x=personality_traits, y=Value, fill = personality_traits)) + 
  geom_violin()+ 
  scale_fill_manual(values = colors) +
  theme(axis.text.x = element_text(angle = 90, hjust = 1, size = 18), axis.title.x = element_text(size = 20),             
    axis.title.y = element_text(size = 20),   
    axis.text.y = element_text(size = 18),  legend.position = "none")
violin_plot 
violin_plot_jitter <- violin_plot + geom_jitter(color = '#5B6467')
violin_plot_jitter
violin_plot_boxplot<- violin_plot + geom_boxplot(width=0.1, colour="darkgrey", fill="lightgrey")
violin_plot_boxplot
```



