---
title: "solution_by_hiuyan"
output: md_document
date: "2025-03-31"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, warning=FALSE, message = FALSE)
```

## Dataset Manipulation 


```{r}
library(tidyverse)
file <- "standard_rating_list.txt"
df <- read_fwf(file=file, 
               fwf_empty(file, 
                        col_names=c("ID", "Name", "Fed", "Sex", "Tit", "WTit", "OTit", "FOA", "APR25", "Gms", "K", "Birthday", "Flag")),
                        skip=1) %>%
      mutate(Fed = na_if(Fed, "NON")) %>%
      drop_na(Birthday, APR25, Fed) %>% # remove rows without birthday or rating
      # filter out rows with invalid birthday year
      filter(Birthday > 1900) %>%
      select(Name, Fed, APR25, Birthday) %>%
      # remove irrelevant columns
      mutate(# using cut already create factor-typed column
             bin = cut(2024-Birthday, breaks=c(1,16,25,35,46,Inf), labels=c("below 16", "16-24", "25-34", "35-45", "above 45"))
             ) %>%
      drop_na(bin)

by_country_by_age <- group_by(df, Fed, bin) %>%
  summarise(mean_rating=mean(APR25, na.rm=TRUE), .groups="drop") %>%
  pivot_wider(names_from=bin, values_from=mean_rating) %>%
  select("Fed", "below 16", "16-24", "25-34", "35-45", "above 45")

by_country <- group_by(df, Fed) %>%
  summarise(mean_rating=mean(APR25, na.rm=TRUE)) %>%
  arrange(desc(mean_rating)) 

final_df <- left_join(by_country, by_country_by_age, by="Fed") %>%
  arrange(desc(mean_rating)) %>%
  slice_head(n=10)

knitr::kable(final_df, format = "pipe", caption="table sorted by average rating of each federation (Top 10)")
```

## Data Visualisation

- Ridgeline Plots

```{r}
library(ggridges)
ridgePlot <- df %>%
  filter(Fed %in% c("CUB", "BIH", "MYA","FIN","SRB")) %>%
  ggplot(aes(x = APR25, y = as.factor(bin), fill = ..x..)) +  # Gradient fill based on APR25 rating
  geom_density_ridges_gradient(scale = 1, rel_min_height = 0.01) +  
  facet_wrap(~ Fed, scales = "free_y") +  # One plot per federation
  scale_fill_viridis_c(name = "Rating", option = "C") +  # Apply viridis color scale
  labs(title = "Rating distributions of each Top 5 Federation (by Age category)",
       x = "APR25 Rating",
       y = "Age Group",
       fill = "Rating Intensity") +
  theme(legend.position = "right",
        panel.spacing = unit(2, "lines"))

ridgePlot
```

- Heatmap
```{r}
library(reshape2)

age_groups <- c("below 16", "16-24", "25-34", "35-45", "above 45") # for strict ordering

df_heatmap_pivot <- by_country_by_age %>%
  filter(Fed %in% c("NON", "CUB", "BIH", "MYA","FIN","SRB", "KOS", "NED", "UKR", "GER")) %>%
  select(Fed, all_of(age_groups)) %>%
  pivot_longer(cols = all_of(age_groups), 
               names_to = "Age", 
               values_to = "APR25")

df_heatmap_pivot$Age <- factor(df_heatmap_pivot$Age, levels = age_groups) # to fix the age order

ggplot(df_heatmap_pivot, aes(x = Age, y = Fed, fill = APR25)) +
  geom_tile() +  # heatmap needs tiles
  scale_fill_gradientn(colors = colorRampPalette(c("yellow","deepskyblue2", "deepskyblue4"))(20),
                       name = "Mean Rating") + # more fine-grained palette
  labs(title = "Mean rating by Federation and Age categories", 
       x = "Age category", 
       y = "Federation") + 
  theme(axis.text.x = element_text(angle = 45, hjust = 1))  # rotate x-axis and align with plot)

```


