---
title: "Yuuunji"
output: md_document
---

### Importing Datasets

```{r cars}

library(tidyr)
library(dplyr)
library(readr)
results <- read_csv("tabelles_of_intrest/results.csv")
races<- read_csv("tabelles_of_intrest/races.csv")
drivers<- read_csv("tabelles_of_intrest/drivers.csv")
driver_standings<- read_csv("tabelles_of_intrest/driver_standings.csv")
constructors<- read_csv("tabelles_of_intrest/constructors.csv")
```

### Finding Top 10 racers from 2000 - 2020 in result.csv

```{r pressure, echo=FALSE}

races <- races %>% select(year, raceId)
result <-results %>% select(raceId, constructorId, driverId)

win1 <- driver_standings %>%
  select(raceId,driverId,wins) %>%
  left_join(., races, by = "raceId") %>%
  left_join(., result, by = c("raceId", "driverId")) %>%
  group_by(driverId, year, constructorId) %>%
  filter(year <2021 & year > 1999 & !is.na(constructorId)) %>%
  summarise(total=max(wins))

win2 <- win1 %>%
  group_by(driverId) %>%
  summarise(total=sum(total)) %>%
  arrange(desc(total)) %>%
  top_n(10,total)

win3 <- win1%>% filter(driverId %in% win2$driverId & total >0)

```


### Finding names corresponding to ID

```{r}
top_drivers <- drivers %>% filter(driverId %in% win3$driverId) %>%
  select(driverId,forename,surname,nationality) 

con_names<- constructors %>% filter( constructorId %in% win3$constructorId) %>% select(constructorId,name)

win3 <- full_join(win3,top_drivers, by = "driverId")
win3 <- full_join(win3,con_names, by = "constructorId")
```

### Visualisation

```{r} 

library(plotly)

library(ggplot2)


fig <- plot_ly(win3, x = ~total, y = ~surname, type =
'bar',orientation = 'h', name = ~name, color=~name, text =
~nationality, xother = ~forename, hovertemplate = paste( "Name:
%{xother} %{y}<br>", "Nationality: %{text}<br>", "Year: %{}<br>", "Wins:
%{x}<br>", "Constructor: %{color}<br>", "<extra></extra>" ))

fig <- fig %>% layout(yaxis = list(title = 'Count'), barmode =
'stack')
fig
```
