---
title: "Man's project: 2 Broke Girls"
author: "Henning Lang"
date: "`r format(Sys.time(),'%d %B %Y')`"
output: md_document
---

**Cleaning** 
```{r message=FALSE, warning=FALSE}
rm (list = ls())
cat ("\14")
graphics.off()
```

**Packages** 
```{r message=TRUE, warning=FALSE}
if (!require(ggpubr)) install.packages("ggpubr")
library(ggpubr)
if (!require(dplyr)) install.packages("dplyr")
library(dplyr)
if (!require(tidyverse)) install.packages("tidyverse")
library(tidyverse)
```

**Insert data (after merging in Excel)**
```{r message=FALSE, warning=FALSE}
setwd ("C:/Users/henni/OneDrive - bwedu/Dokumente/EBPP/Semester_5/Advanced R/Man's Projekt")
data <- read.csv2 ("Datensatz.csv")
```


**Prepare dataset**
```{r}
names (data) <- c("date", "episode", "title", "viewers_million", "viewers_change", "ratings")
data <- data[-139, ]                      # NA-Zeile entfernt
table (data$ratings)                      # Sieht gut aus
data$episode <- as.numeric(data$episode)  # episode should be numeric
```

**Add column season**
```{r}
data$season <- NA
data$season   [1:24] <- 1
data$season  [25:48] <- 2
data$season  [49:72] <- 3
data$season  [73:94] <- 4
data$season [95:116] <- 5
data$season[117:138] <- 6
```

**Change column episode**
```{r}
data$episode   [1:24] <- 1:24
data$episode  [25:48] <- 1:24
data$episode  [49:72] <- 1:24
data$episode  [73:94] <- 1:22
data$episode [95:116] <- 1:22
data$episode[117:138] <- 1:22
```

**Overview about dataset**
```{r}
head(data)
summary(data)
```

**Create plot**
```{r}
data %>%
  ggplot(aes(x=episode, y=ratings, group = season)) +
  geom_line(aes(color = factor(season)), linewidth = 1.3) +
  geom_point(aes(colour = factor(season)), shape=21, color="black", fill="#69b3a2", size=1) +
  theme_minimal() +
  theme(panel.grid.major.y = element_blank(),
        panel.grid.minor.y = element_blank(),
        axis.title.x=element_blank(),
        axis.text.x=element_blank(),
        axis.ticks.x=element_blank(),
        legend.background = element_rect(fill = "white", colour = "black")) +
  scale_color_manual(values=c("lightslateblue", "lightblue1", "lightgoldenrod4", "mediumblue", "lightcyan3", "lightcyan4")) +
  xlab (" ") +
  ylab ("Ratings") + 
  ggtitle("Ratings of 2 Broke Girls",
          subtitle = "Ratings from The Nielson Company (2016)") +
  labs (color = "Season")
```


