---
title: "Plot"
author: "ManCao"
date: "2023-03-27"
output: md_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
```

## Sonja's project

```{r}
knitr::opts_chunk$set(echo = FALSE)
#Sonja's project

#packages
if (!require(ggpubr)) install.packages("ggpubr")
library(ggpubr)
if (!require(dplyr)) install.packages("dplyr")
library(dplyr)
if (!require(tidyverse)) install.packages("tidyverse")
library(tidyverse)
if (!require(ggrepel)) install.packages("ggrepel")
library(ggrepel)
if (!require(lubridate)) install.packages("lubridate")
library(lubridate)

# set directory
setwd("D:/WiSe2022-23/R2Course/Advanced-data-processing-with-R/Projects/sonji-uni")
getwd()

# read data
dataRaw <- read.csv("I4S_workingMemory_2023-02-26.csv",header=TRUE,sep=';')

# set timestamp
dataRaw$timestamp <- as.POSIXct(dataRaw$timestamp/1000, origin="1970-01-01")
dataRaw$timestamp <- trunc(dataRaw$timestamp)
dataRaw$timestamp<- as_datetime(dataRaw$timestamp)

# remove all instructions and examples
data<- dataRaw %>% 
  select(!time_elapsed & !trial_type) %>%
  filter((trial_index >14 & trial_index<75) |(trial_index >87 & trial_index<148)|(trial_index >160 & trial_index<=220))

# n_back sub_dataframe
back_1<-dataRaw %>% 
  select(!time_elapsed & !trial_type) %>%
  filter(trial_index >14 & trial_index<75)%>%
  group_by(SID)%>%
  mutate(same_stim= lag(stim,1),oneBack= stim==same_stim)%>%
  drop_na(oneBack)%>%
  mutate(correct=(oneBack&response==0)|(!oneBack&is.na(response)))%>%
  summarise(accuracy =mean(correct,na.rm=T),timezone=format(min(timestamp),'%H:%M'),rt=rt)%>%
  arrange(timezone)
back_2<- dataRaw %>% 
  select(!time_elapsed & !trial_type) %>%
  filter(trial_index >87 & trial_index<148)%>%
  group_by(SID)%>%
  mutate(same_stim= lag(stim,2),twoBack= stim==same_stim)%>%
  drop_na(twoBack)%>%
  mutate(correct=(twoBack&response==0)|(!twoBack&is.na(response)))%>%
  summarise(accuracy =mean(correct,na.rm=T),timezone=format(min(timestamp),'%H:%M'),rt=rt)%>%
  arrange(timezone)


back_3<- dataRaw %>% 
  select(!time_elapsed & !trial_type) %>%
  filter(trial_index >160 & trial_index<=220)%>%
  group_by(SID)%>%
  mutate(same_stim= lag(stim,3),threeBack= stim==same_stim)%>%
  drop_na(threeBack)%>%
  mutate(correct=(threeBack&response==0)|(!threeBack&is.na(response)))%>%
  summarise(accuracy =mean(correct,na.rm=T),timezone=format(min(timestamp),'%H:%M'),rt=rt)%>%
  arrange(timezone)


# Plot efficiency against timestamp
p1<- ggplot(back_1, aes(x=timezone, y=rt,fill=timezone)) +
  geom_point()+
  labs(x = "Timestamp", y = "RT") +
  theme_bw()+
  theme(
    panel.border = element_blank(),
    panel.grid.major = element_blank(),
    panel.grid.minor = element_blank(),
    panel.background = element_rect(fill = NA))
print(p1)
  
p2<- ggplot(back_2, aes(x=timezone, y=rt,fill=timezone)) +
  geom_point() +
  labs(x = "Timestamp", y = "RT") +
  theme_bw()+
  theme(
    panel.border = element_blank(),
    panel.grid.major = element_blank(),
    panel.grid.minor = element_blank(),
    panel.background = element_rect(fill = NA))
print(p2)

p3<- ggplot(back_3, aes(x=timezone, y=rt,fill=timezone)) +
  geom_point() +
  labs(x = "Timestamp", y = "RT") +
  theme_bw()+
  theme(
    panel.border = element_blank(),
    panel.grid.major = element_blank(),
    panel.grid.minor = element_blank(),
    panel.background = element_rect(fill = NA))
print(p3)

# Plot accuracy against timestamp
p4<-ggplot(back_1, aes(x=timezone, y=accuracy)) +
  geom_point()
  labs(x = "Timestamp", y = "Accuracy") +
  scale_y_continuous(label=scales::percent)+
  theme_bw()+
  theme(
    panel.border = element_blank(),
    panel.grid.major = element_blank(),
    panel.grid.minor = element_blank(),
    panel.background = element_rect(fill = NA))
print(p4)


p5<-ggplot(back_2, aes(x=timezone, y=accuracy)) +
  geom_point()
labs(x = "Timestamp", y = "Accuracy") +
  scale_y_continuous(label=scales::percent)+
  theme_bw()+
  theme(
    panel.border = element_blank(),
    panel.grid.major = element_blank(),
    panel.grid.minor = element_blank(),
    panel.background = element_rect(fill = NA))
print(p5)

p6<-ggplot(back_3, aes(x=timezone, y=accuracy)) +
  geom_point()
labs(x = "Timestamp", y = "Accuracy") +
  scale_y_continuous(label=scales::percent)+
  theme_bw()+
  theme(
    panel.border = element_blank(),
    panel.grid.major = element_blank(),
    panel.grid.minor = element_blank(),
    panel.background = element_rect(fill = NA))
print(p6)

```

