---
title: "Solution Bernhard"
author: "Eric Offermann"
date: '2023-01-23'
output: html_document
---
## Project 3
### Course: R2 -  Advanced data processing with R
### Information of the task can be found on the following Webpage: *https://dr-eberle-zentrum.github.io/Advanced-data-processing-with-R/Projects/bernhard-ebersbach/project-description.html*
```{r, echo = F, message=FALSE, warning=FALSE}
#Project of Bernhard
#16.01.2023
library(tidyverse)
library(ggplot2)
library(dplyr)
library(scales)
#Load the data
dir = "D:/Eric/Documents/Uni_Tuebingen_Kurse/5. Semester/Kurs R2/Project3_RKurs"
setwd(dir)
data = read.csv2("nmin_jena_2022.csv")

#View(data)
#which( colnames(data)=="Nmin [mg/kg]")

names(data)[10] <- "Sowndiv"
names(data)[15] <- "Numleg"
names(data)[8] <- "Nmin"

df = data[c(8,10,15)]


df1 = df %>%
  mutate(sowndiv1 = case_when(Sowndiv <= 1 ~ '1',
                            Sowndiv <= 4  ~ '2',
                            Sowndiv <= 16  ~ '3',
                            Sowndiv > 16 ~ '4')) %>%
  mutate(Numleg1 = case_when(Numleg <=1  ~ '1',
                            Numleg <=3  ~ '2',
                            Numleg <=5  ~ '3',
                            Numleg <=8  ~ '4',
                            Numleg <=12  ~ '5', 
                            Numleg > 12  ~ '6')) %>%
  group_by(Numleg1, sowndiv1) %>%
  summarise(MW = mean(as.numeric(Nmin), na.rm = T),
             error = sd(as.numeric(Nmin), na.rm = T) / sqrt(n()),
             .groups = "drop") %>% 
  
  #summarise(Abweichung = mean(as.numeric(Nmin), na.rm = T),
            #SDW = sd(as.numeric(Abweichung), na.rm = T))
  ## Hier gibt es die Probleme mit der Standardabweichung. Mit dem Script rechnet
  ## es beispielsweise nur die Abweichung und nicht die Standardweichung
  complete(Numleg1, sowndiv1)
  
```



```{r hallo, echo=FALSE,message=FALSE, warning=FALSE}
df1 %>%
  replace_na(list(Nmin="0"))%>%
  ggplot(aes( y=as.numeric(MW), x=Numleg1, fill=as.factor(sowndiv1)) )+ #Hier müsste man irgendwie alle Modelle auf eine Achse laden können
  geom_bar(position = "dodge", stat = "identity") +
  geom_errorbar(aes(ymin=MW-error, ymax=MW+error), width=.2,
               position=position_dodge(.9)) +
  #geom_errorbar(position = position_dodge(width= 0.9),aes(ymin=Abweichung-mean(SDABW), ymax=Abweichung+mean(SDABW)), width=.2)+
  labs(x = "Number of legume species",
       y = expression("N"[min]*"[mg/kg]"),
       fill = "Diversity level (sowndiv)")+
  ggtitle("Titel des Diagramms")+
  scale_x_discrete(labels = c("0-1","2-3","4-5","6-8","9-12","über 12"))+
  scale_fill_discrete(name = "Diversity level (sowndiv)", labels = c("0-1", "2-4", "4-16", ">16"))
  geom_text(position = position_dodge(width= 1), aes(label = scales::comma(round(Nmin, 1))), hjust = 0.7, vjust = 0.23, angle = 90)#+
  #scale_fill_manual(values = c("slategray1", "skyblue3", "skyblue4", "royalblue3", "royalblue4", "navy"))


```

