---
title: "Projekt von Jan"
author: "Eric Offermann"
date: '2022-12-06'
output:
  html_document: default
  pdf_document: default
---


```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```
# Lösungen zum Projekt von Jan


```{r, echo = FALSE, message=FALSE, warning=FALSE}
library(tidyverse)
library(ggplot2)
library(dplyr)
library(scales)

wd = setwd("D:/Eric/Documents/Uni_Tuebingen_Kurse/5. Semester/Kurs R2/Aufgabe_1/Advanced-data-processing-with-R/Projects/jan-boethling")

csv_jan = read.csv("Data_Project_Jan.csv")


#Umbenennen der Variablen
names(csv_jan)[8] <- "Country"
names(csv_jan)[10] <- "Year"
names(csv_jan)[24] <- "Cases"
#Löschen der nicht benutzten Spalten
#Hier über Index
#Dafür muss allerdings jedes Mal die Tabelle geöffnet werden und geschaut werden an welcher Stelle die Column ist

df = csv_jan[-c(1:7,9,11:23,25:34)]
```

## Aufgabe 1

```{r hallo, echo=FALSE,message=FALSE, warning=FALSE}
df %>%
  group_by(Year)%>%
  summarise(Cases = sum(Cases, na.rm = T), na.rm = T) %>%
  
  ggplot(aes(Year, Cases))+
  geom_line(color = "red", linewidth = 2)+
  labs(x = "",
       y = "HIV-Fallzahlen")+
  ggtitle("Anstieg der HIV-Fallzahlen über die Jahre")+
  scale_y_continuous(labels = comma)
```

## Aufgabe 2

```{r pressure, echo=FALSE, message=FALSE, warning=FALSE}
#Aufgabe 2
top5 <- df %>% 
  #%>%# Top N highest values by group
  group_by(Country) %>%
  summarise(Cases = max(Cases, na.rm = T)) %>%
  #arrange(desc(Cases)) %>% 
  slice_max(Cases, n = 5)

df %>%
  filter(Country %in% top5$Country) %>%
  mutate(Country = recode(Country,"United Republic of Tanzania" = "Tansania",
                                    "India" = "Indien",
                                    "South Africa" = "Südafrika",
                          "Kenya" = "Kenia"))%>%
  
  ggplot(aes(x = reorder(Year, Cases), y = Cases, group = Country))+ #Ziel: Hier keine Colorscale sondern normale Farbzuweisung pro Jahr
  geom_line(aes(color= as.factor(Country)),linewidth = 0.8)+
  labs(x = "",
       y = "HIV-Fallzahlen",
       fill = "")+ #Legenden-Titel soll noch angepasst werden können
  ggtitle("HIV-Zahlen verschiedener Jahre für die am stärksten betroffenen Länder")+
  scale_y_continuous(labels = comma)+
  scale_color_discrete("")+
  theme(axis.text.x = element_text(angle = 45, vjust = 0.5))

```

## Aufgabe 3

```{r Moien, echo=FALSE, message=FALSE, warning=FALSE}

top5 <- df %>% 
  #%>%# Top N highest values by group
  group_by(Country) %>%
  summarise(Cases = max(Cases, na.rm = T)) %>%
  #arrange(desc(Cases)) %>% 
  slice_max(Cases, n = 5)

df %>%
  filter(Country %in% top5$Country) %>%
  mutate(Country = recode(Country,"United Republic of Tanzania" = "Tansania",
                                    "India" = "Indien",
                                    "South Africa" = "Südafrika",
                          "Kenya" = "Kenia"))%>%
  
  ggplot(aes(x = reorder(Country, -Cases), y = Cases, fill = as.factor(Year)))+
  geom_bar(position = "dodge", stat = "identity")+
  labs(x = "",
       y = "HIV-Fallzahlen",
       fill = "Jahre")+ 
  ggtitle("Veränderung der HIV-Zahlen der am stärksten betroffenen Länder")+
  scale_y_continuous(labels = comma)+
  theme(axis.text.x = element_text(angle = 45, vjust = 0.5))

  
```

