---
title: "thomaskleiser"
author: "thomaskleiser"
output: "html_document"

---



```{r data_importation_manipulation_and_calculation, results = 'hide'}
# Solution attempt for Eric's Project by Thomas

# loading the neccessary libraries:
library(readr)
library(tidyverse)
library(devtools)

# importing the data using read_xcel()
corona_eu <- read_csv(url("https://opendata.ecdc.europa.eu/covid19/nationalcasedeath_eueea_daily_ei/csv/data.csv")) %>%
  rename("country" = "countriesAndTerritories",
         "population_2020" = "popData2020") %>%
  na.omit()

# filtering for EU-countries with filter()
corona_eu_summary <- corona_eu %>% 
  filter(country != "Norway" & country != "Iceland" & country != "Liechtenstein") %>%
# calculating the number of cases and deaths per country with group_by() and mutate():
  group_by(country) %>%
  summarize(cases_total = sum(cases),
            deaths_total = sum(deaths),
            population = mean(population_2020)
            ) %>%
  mutate(cases_total_per_capita = cases_total / population * 100,
         deaths_total_per_capita = deaths_total / population * 1000)

# calculating the mean number of cases and deaths per capita:
mean_cases_total_per_capita <- corona_eu_summary %>%
  summarise(mean_cases_total_percapita = mean(cases_total_per_capita)
            ) %>%
  pull()

mean_deaths_total_per_capita <- corona_eu_summary %>%
  summarise(mean_deaths_total_percapita = mean(deaths_total_per_capita)
            ) %>%
  pull()

```



```{r visualization_of_cases}
# visualiszing the number of cases with ggplot() and geom_bar()
ggplot(corona_eu_summary, aes(x = reorder(country, desc(cases_total_per_capita) ), y = cases_total_per_capita)) +
  geom_bar(stat = "identity", fill = "lightblue") +
  geom_hline(yintercept = mean_cases_total_per_capita, linetype = "dotted") +
  geom_text(x = "Malta", y = 42.5, label = "EU average") +
  labs(title = "Number of reported Sars-CoV-2 Cases per 100 Inhabitants in EU, 2020-2022",
       caption = "Source: European Center for Disease Prevention and Control",
       x = element_blank(),
       y = element_blank()) +
  theme_classic() +
  theme(axis.text = element_text(angle = 90))

```

```{r visualization_of_deaths}
# visualizing the number of deaths with ggplot() and geom_bar()
ggplot(corona_eu_summary, aes(x = reorder(country, desc(deaths_total_per_capita) ), y = deaths_total_per_capita)) +
  geom_bar(stat = "identity", fill = "lightgreen") +
  geom_hline(yintercept = mean_deaths_total_per_capita, linetype = "dotted") +
  geom_text(x = "Malta", y = 2.95, label = "EU average") +
  labs(title = "Number of reported Deaths due to Sars-CoV-2 per 1000 Inhabitants in EU, 2020-2022",
       x = element_blank(),
       y = element_blank(),
       caption = "Sources: European Center for Disease Prevention and Control") +
  theme_classic() +
  theme(axis.text = element_text(angle = 90))
```

```{r cases_vs_bip}

bip_eu <- data.frame("country" = c("Luxembourg","Ireland","Norway","Denmark","Sweden",
                                   "Netherlands","Finland","Austria","Belgium","Germany",
                                   "France","Italy","Malta","Cyprus","Spain",
                                   "Slovenia","Estonia","Czechia","Portugal","Lithuania"
                                   ,"Slovakia","Latvia","Greece","Hungary","Poland",
                                   "Croatia","Romania","Bulgaria"),
                     "bip_per_capita" = c(114370,84940,75360,57520,51630,
                                          48840,45370,44970,43680,43290,
                                          36660,30040,28220,26030,25460,
                                          24680,23060,22270,20530,19760,
                                          17820,17450,17140,15870,15050,
                                          14701,12501,9850)
                     )

corona_bip_eu <- left_join(corona_eu_summary,bip_eu, by = "country")

```



```{r visualisation_of_cases_vs_bip}

ggplot( corona_bip_eu, aes(x = bip_per_capita, y = cases_total_per_capita) ) +
  geom_point() +
  geom_smooth(method = "lm",
              se = FALSE,
              color = "red") +
  labs(title = "Relation between Sars-CoV-2 cases and GDP",
       subtitel = "measeured in reported cases per capita and GDP per capita",
       x = "GDP per Capita (in Euro)",
       y = "Reported Sars-CoV-2 Cases",
       caption = "Source: European Center for Disease Prevention and Control, Statista") +
  theme_classic() +
  theme(plot.title = element_text(face = "bold",
                                  hjust = 0.5),
        axis.title = element_text(face = "bold",
                                  size = 11),
        )

cor(corona_bip_eu$cases_total_per_capita, corona_bip_eu$bip_per_capita)

```



```{r visualisation_of_deaths_vs_bip}

ggplot( corona_bip_eu, aes(x = bip_per_capita, y = deaths_total_per_capita) ) +
  geom_point() +
  geom_smooth(method = "lm",
              se = FALSE,
              color = "red") +
    labs(title = "Relation between Sars-CoV-2 deahts and GDP",
         subtitel = "measeured in reported deaths due to  Sars_CoV-2 cases per capita and GDP per capita",
         x = "GDP per Capita (in Euro)",
         y = "Reported deaths due to Sars-CoV-2",
       caption = "Source: European Center for Disease Prevention and Control, Statista") +
  theme_classic() +
  theme(plot.title = element_text(face = "bold",
                                  hjust = 0.5),
        axis.title = element_text(face = "bold",
                                  size = 11)
        )

cor(corona_bip_eu$deaths_total_per_capita, corona_bip_eu$bip_per_capita)

```
