---
title: "t1mge's_solution_for_When_dargonflies_fly"
author: "t1mge"
date: "2025-06-10"
output: md_document
---

Goal: "To find out under which weather conditions Aeshna mixta prefers to fly"

```{r setuo}
library(tidyverse)
```

# Data manipulation of the weather data
```{r}
weather_data <- read_delim("https://raw.githubusercontent.com/Dr-Eberle-Zentrum/Data-projects-with-R-and-GitHub/refs/heads/main/Projects/paula0013/Weather_Data_Poland.csv"
                           , delim = ",")
rev_weather_data <- weather_data %>% 
  slice(-1) %>% # removing the first row. This corresponds to the row with units
  
  select("Time", "Temp", "Wind Speed", "True Dir.") %>% #reducing the dataset to the four given varaible
  
  separate(Time, into = c("date", "time"), sep = "(?<=\\d{4}-\\d{2}-\\d{2})\\s(?=\\d{2}:\\d{2}:\\d{2})") %>% # Seperating the time column into time and date with an regex expression trageting specifically the space inbetween 
  mutate(
  Temp = as.numeric(Temp),
  `Wind Speed` = as.numeric(`Wind Speed`),
  `True Dir.` = as.numeric(`True Dir.`)
) %>% 
  mutate(
    date = ymd(date),
    time = hms(time),
    hour = hour(time)
  ) %>% # here we convert time and date into date and time of day objects and extract the hours as a numerical value to make it easier to handle them later and average them in the next step
filter(date >= as.Date("2024-08-01") & date <= as.Date("2024-10-01")) %>% # Here I am filtering the date so that they align with the catch period
  mutate(
    period = case_when(
      hour >= 10 & hour < 14 ~ "Morning",
      hour >= 14 & hour < 17 ~ "Afternoon",
    )
  ) %>% #case_when is similar to if_else function but more than one conditions can be checked, this avoids nesting and is particular functional and readable when needing to compare even more conditions, see later for the compass direction
  filter(!is.na(period))%>% 
  group_by(date, period) %>% 
  summarise(
    mean_temp = mean(Temp, na.rm = TRUE),
    mean_wind = mean(`Wind Speed`, na.rm = TRUE),
    mean_winddir = mean(`True Dir.`, na.rm = TRUE),
  ) %>% #Here we summarize the temp, windspeed and true dir in respect to the date and period 
  ungroup() %>% 
  mutate(
    compass_dir = case_when(
      mean_winddir >= 348.75 & mean_winddir <= 360 ~ "N",
      mean_winddir >= 0 & mean_winddir <= 11.24 ~ "N",
      mean_winddir >= 11.25 & mean_winddir <= 33.74 ~ "NNE",
      mean_winddir >= 33.75 & mean_winddir <= 56.24 ~ "NE",
      mean_winddir >= 56.25 & mean_winddir <= 78.74 ~ "ENE",
      mean_winddir >= 78.75 & mean_winddir <= 101.24 ~ "E",
      mean_winddir >= 101.25 & mean_winddir <= 123.74 ~ "ESE",
      mean_winddir >= 123.75 & mean_winddir <= 146.24 ~ "SE",
      mean_winddir >= 146.25 & mean_winddir <= 168.74 ~ "SSE",
      mean_winddir >= 168.75 & mean_winddir <= 191.24 ~ "S",
      mean_winddir >= 191.25 & mean_winddir <= 213.74 ~ "SSW",
      mean_winddir >= 213.75 & mean_winddir <= 236.24 ~ "SW",
      mean_winddir >= 236.25 & mean_winddir <= 258.74 ~ "WSW",
      mean_winddir >= 258.75 & mean_winddir <= 281.24 ~ "W",
      mean_winddir >= 281.25 & mean_winddir <= 303.74 ~ "WNW",
      mean_winddir >= 303.75 & mean_winddir <= 326.24 ~ "NW",
      mean_winddir >= 326.25 & mean_winddir <= 348.74 ~ "NNW",
    )
  )
```


# Data manipulation of the catch data
```{r}

fang_data <- read_delim("https://raw.githubusercontent.com/Dr-Eberle-Zentrum/Data-projects-with-R-and-GitHub/refs/heads/main/Projects/paula0013/Fangdaten_Poland.csv") 
rev_fang_data <- fang_data %>% 
  na.omit() %>% 
  group_by(Datum, Uhrzeit, Geschlecht) %>% 
  summarise(Anzahl = n()) %>% 
  ungroup() %>% 
  mutate(
    Datum = dmy(Datum))

weather_fang_data2 <-
  left_join(rev_weather_data, rev_fang_data, by = c("date" = "Datum", "period" = "Uhrzeit"))
# left joining the weather data to the fang data and kicking out the evening catches with the na.omit function

#weather_fang_data2 <-
 # left_join(rev_fang_data, rev_weather_data, by = c("Datum" = "date", "Uhrzeit" = "period")) %>% 
  #na.omit()# left joining the weather data to the fang data and kicking out the evening catches with the na.omit function


view(weather_fang_data2)

```


# Plotting of the data
```{r}
view(weather_fang_data2)

# 1) Your a/b axis‐mapping
ylim.prim <- c(0, 2)
ylim.sec  <- c(0, 40)
b <- diff(ylim.prim) / diff(ylim.sec)
a <- ylim.prim[1] - b * ylim.sec[1] #I found this while searching for how to implement a 2nd y-aixs on stack-overfolw. I think it scales the axis but if you want to know how it is working please look it up here: https://stackoverflow.com/questions/3099219/ggplot-with-2-y-axes-on-each-side-and-different-scales

# 2) Choose 8 evenly spaced dates across your range
all_dates    <- sort(unique(weather_fang_data2$date))
break_dates  <- seq(min(all_dates), max(all_dates), length.out = 8)
# round them to actual dates in your data
break_dates  <- as.Date(round(break_dates), origin = "1970-01-01")

# 3) Build labels lookup with date, compass_dir, and mean_wind
lab_df <- weather_fang_data2 %>%
  distinct(date, compass_dir, mean_wind) %>%
  mutate(
    xlabel = paste0(
      date,            "\n",          # line 1: actual date
      compass_dir,     "\n",          # line 2: compass direction
      round(mean_wind, 1), " m/s"     # line 3: mean wind speed
    )
  )

# 4) Extract only the labels for your chosen break_dates
label_map <- lab_df %>%
  filter(date %in% break_dates) %>%
  select(date, xlabel) %>%
  deframe()  # makes a named vector: names = dates, values = strings

ggplot(weather_fang_data2, aes(x = date)) +

  geom_col(aes(y = Anzahl, fill = Geschlecht), position = "stack") +

  geom_smooth(aes(y = a+b*mean_temp, color = period)) +
  
  scale_y_continuous(
    "number of individuals", 
    breaks = c(0,1,2), 
    sec.axis = sec_axis(~ (. - a)/b, 
                        name = "Temperature [°C]")
    )+
  scale_color_manual(
    name = "period",
    values = c("Morning" = "blue", "Afternoon" = "red")
  ) +
  
  scale_x_date(
    breaks = as.Date(names(label_map)),  # the eight dates
    labels = label_map        # their three-line labels 
  ) +
  theme_minimal() +
  theme(
    axis.title.y.left  = element_text(color = "black"),
    axis.title.y.right = element_text(color = "blue"),
    axis.text.x        = element_text(
      vjust      = 1,
      lineheight = 0.9,
      size       = 8)
  )
```





```{r}
  '# This is how you would rename the columns I choose not to do it because the long name are very cluncky and dont provide any value during the creation the plots
  rename("Date in yyyy-MM-dd" = date,
         "Time in hh:mm:ss" = time,
         "Temperature in Celsius" = Temp, 
         "Wind speed in m/s" = "Wind Speed",
         "Wind direction in degrees" = "True Dir.") %>% #renaming the columns
'# 
```


