---
title: "Soil Data Analysis"
author: "Martin"
date: "2024-03-15"
output: md_document
---


```{r, echo=FALSE}
# silent load of libraries
suppressMessages(library(tidyverse))

# set working directory to script location
setwd(dirname(rstudioapi::getSourceEditorContext()$path))

```

# (1) Data import and clean up

```{r data.import}
# read file
soilData <-
  read_delim("SoilData.csv",
             delim=";",
            # (1.5) deal with NA values
            na = c("","NA","99999","99999,99"),
            show_col_types  = F) |>
  # (1.1) drop KAKpot2 column
  select(-`KAKpot 2`) |>
  # (1.2) drop numbers in column names
  rename_with(~str_replace(., "_\\d+$", ""))

soilDataHeader <-
  soilData |>
  # get unit information
  slice(1) |>
  # join unit and column information rowwise
  pivot_longer(cols = everything(), names_to = "col", values_to = "unit") |>
  # (1.4) fix typo in header
  mutate(col = ifelse(col == "Expozition","Exposition",col)) |>
  # (1.3) append unit to column name if not empty
  transmute(
    header = str_c(
      str_trim(col),
      ifelse(str_detect(unit, "^\\s*\\[\\s*\\]\\s*$"),"","_"),
      ifelse(str_detect(unit, "^\\s*\\[\\s*\\]\\s*$"),"",str_remove_all(unit,"\\s"))
      )) |>
  pull(header)

# cleanup data
soilDataRefined <-
  soilData |>
  setNames(soilDataHeader) |>
  slice(-1) |>
  # reparse data types of all columns
  mutate(across(everything(), \(x) parse_guess(x,locale=locale(grouping_mark = ".",decimal_mark = ",")))) |>
  # (1.6) final computations
  mutate(
    `base_saturation_[%]` = `Kationen_[mmol/kg]` / `KAKpot_[mmol/kg]`,
    `SOM_[%]` = `Corg_[%]` * 1.72
  )

# print nice table
soilDataRefined |>
  slice_head(n=5) |>
  knitr::kable()

```
## (1.7) get SUT statistics

```{r check.for.1}
soilDataRefined |>
  transmute(`SUT==100%` =
              case_when(
                near(`S+U+T_[%]`,100) ~ "exact",
                (!near(`S+U+T_[%]`,100) & `S+U+T_[%]`<100) ~ "less",
                TRUE ~ "more"
              )) |>
  group_by(`SUT==100%`) |>
  count() |> 
  ungroup() |> 
  knitr::kable()
```

# (2) visualization

## (2.1) stacked barplot

```{r stacked.barplot}
soilDataRefined |>
  filter( Profil %in% c(55,71,102,109)) |>
  group_by(Profil) |>
  slice_max(Horizont, n = 1) |>
  pivot_longer(cols = str_c(c("Ca","Mg","Kationen"),"_[mmol/kg]"),
               names_to = "Ion", values_to = "value") |>
  mutate(Ion = str_remove(Ion,"_\\[mmol/kg\\]")) |>
  # plotting
  ggplot( aes(x = factor(Profil), y=value, fill=Ion)) +
  geom_bar( stat="identity") +
  labs(title = "Kationen in tiefstem Horizont",
       x = "Profil",
       y = "Konzentration [mmol/kg]") +
  # set fill color to viridis palette
  scale_fill_viridis_d(option = "D")
```

## (2.2) pie chart of grain sizes

```{r pie.chart}

soilDataRefined |>
  filter(Profil %in% c(82,111,134),
         Horizontbezeichnung=="Ah") |>
  select(Profil, `S_[%]`, `U_[%]`, `T_[%]`) |>
  pivot_longer(cols = -Profil,
               names_to = "GrainSize", values_to = "value") |>
  mutate(GrainSize = str_remove(GrainSize,"_\\[\\%\\]")) |>
  mutate(
    GrainSize = case_when(
      GrainSize == "S" ~ "Sand",
      GrainSize == "U" ~ "Schluff",
      GrainSize == "T" ~ "Ton"
    )) |>
  # add profile to facet name and put in correct order
  mutate(Profil = factor(str_c("Profil ",Profil)) |> fct_reorder(Profil)) |>
  # plotting
  ggplot(aes(x="", y=value, fill=GrainSize)) +
  geom_bar(width = 1, stat = "identity") +
  # make it a pie chart
  coord_polar("y", start=0) +
  theme_void() +
  labs(title = "Korngrößenverteilung",
       fill = "Bodenart",
       x = NULL,
       y = NULL) +
  scale_fill_viridis_d(option = "D") +
  # faceting with label below chart
  facet_wrap(~Profil, strip.position = "bottom") +
  # add label in segments
  geom_text(aes(label = str_c(round(value,1),"%")),
            position = position_stack(vjust = 0.5))
```

## (2.3) location plotting

```{r geo.plot}
#library(terra)
soilDataProjected <-
  soilDataRefined |>
  # convert UTM geo encoding into long/lat-based encoding
  select(East, North) |>
  rename(x=East, y=North) |>
  as.matrix() |>
  terra::vect(crs="+proj=utm +zone=32 +datum=WGS84 +units=m +no_defs") |>
  terra::project("+proj=longlat +datum=WGS84") |>
  terra::geom() |>
  as_tibble() |>
  select(lat = y, long = x) |>
  # join with original table
  bind_cols(soilDataRefined)


library(sf)
#https://r-charts.com/spatial/maps-ggplot2/

map_data("world", "Germany") |>
  ggplot(aes(x = long, y = lat)) +
  geom_polygon(aes(group = group))+
  geom_point(
    data = soilDataProjected,
    aes( x=long, y=lat),
    col="red", size=1
  ) +
  coord_cartesian(xlim=c(8.8,9.1), ylim=c(48,49))
```
