---
output: md_document
---

# Self-control, sleep quality and smartphone usage 

* Data: data_smaschkon_2023-02-11_09-11.xlsx
* Variables: variables_smaschkon_2023-02-11_09-24.csv
* Values: values_smaschkon_2023-02-11_09-24.csv

The data was collected as part of a data collection seminar. The aim was to investigate the relationship between self-control, sleep quality and smartphone usage. 
The first challenge will be to form the scales in order to test hypotheses and visualize the results. The PSQI scale for sleep quality is particularly tricky. 
Sum scores can be created to form a scale for both self-control and smartphone usage. The PSQI scale, on the other hand, is a complex scale, the formation of which is described in the document "assessment, pittsburgh psqi.pdf". However, this may be too complex to work out on your own without further information (alternatively, I can help with the scale formation or pass on my code). 
Once the first steps have been taken and the data or scales have been prepared, various visualizations can be created in which the distributions of the variables are described in various ways or correlations are made visible. 
