---
title: "initial project solution"
output: md_document
date: "2024-12-01"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r pressure, echo=FALSE}
library(ggplot2)
library(dplyr)
library(readxl)
library(tidyr)
tennis_data <- read.csv("C:/Users/Yugua/Desktop/R2/atp_matches_qual_chall_2024.csv")
# data of winner
winner_firstPoint <- tennis_data |>
  select(
    Name = winner_name,
    rank = winner_rank,
    tourney_date,
    surface,
    first_in = w_1stIn,
    first_won = w_1stWon
  )

# data of loser
loser_firstPoint <- tennis_data |>
  select(
    Name = loser_name,
    rank = loser_rank,
    tourney_date,
    surface,
    first_in = l_1stIn,
    first_won = l_1stWon
  )

# combine data of winner and loser, no matter they are loser or winner, just show their name and relevant information
combined_firstPoint <- bind_rows(winner_firstPoint, loser_firstPoint)

# calculate the first point won rate of all players, whose rank is smaller than 50
final_filtered <- combined_firstPoint |>
  na.omit() |>
  group_by(Name, surface) |>
  filter(tourney_date == max(tourney_date, na.rm = TRUE)) |>
  filter(rank < 50) |>
  summarise(
    first_point_won_rate = sum(first_won) / sum(first_in),
    avg_first_in_rate = mean(first_in, na.rm = TRUE),
    rank = min(rank),
    .groups = "drop"
  ) |>
  arrange(rank)


ggplot() +
  
  geom_jitter(data = combined_firstPoint |>
                filter(rank < 50, !is.na(first_in), !is.na(first_won)),
              aes(
                x = Name,
                y = first_won / first_in,
                color = surface
              ),
              width = 0.2, size = 2, alpha = 0.6) +
  
  geom_point(data = final_filtered, 
             aes(
               x = reorder(Name, first_point_won_rate), 
               y = first_point_won_rate, 
               color = surface,
               shape = surface
             ),
             size = 4) +
  scale_shape_manual(values = c("Hard" = 17, "Clay" = 15)) +
  scale_color_manual(values = c("Hard" = "blue", "Clay" = "red")) +
  labs(
    title = "First Point Won Rate with Distribution",
    x = "Name",
    y = "First Point Won Rate",
    color = "Surface",
    shape = "Surface"
  ) +
  theme_minimal() +
  theme(
    axis.text.x = element_text(angle = 45, hjust = 1),
    plot.title = element_text(hjust = 0.5)
  )
```