---
title: "project-description (Jan)"
output: html_document
date: "2022-11-14"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

### HIV data

The Global Health Observatory collects and publishes data related to the ongoing HIV epidemic. I dealt with some of the data sets in the course "Entwurf und Umsetzung von Datenbanken". Apart from that they aren´t connected to my studies in any way.

The data set I want to use can be found here: <https://www.who.int/data/gho/data/indicators/indicator-details/GHO/estimated-number-of-people--living-with-hiv>

Click on the tab that says "Data".
Regarding the data import, there are two tables available — one which tracks the estimated number of people living with HIV per Country every fifth year and the second one includes data for every year. You can change between them with the abstract table symbol above the "FILTERS" button.

We use the second table that includes the data for every year. 

Look at the data, there are many columns that we don´t need. Select and rename the following columns:

- Column Location as Country
- Column Period as Year
- Column FactValueNumeric as Cases

### With the tidy data...
1.
Group by year and sum up all cases in the respective year. 
- Visualize by plotting the sum of all cases in each year against the respective year!
- In which year was the total number of people living with HIV the highest?

2.
Return to the original data.
Look for the 5 countries that have the largest estimated number of HIV cases (irrespective of year), then filter for these countries and plot the number of cases against the year. Be creative, make sure that we can easily distinguish between the countries and look out for trends!
Any revelations comparing results 1 and 2?

3.
Create a barplot:
- Select and use the years 2000, 2005, 2010, 2015, 2020 on the x-Axis (use these years as subgroups)
- Each subgroup should contain the 5 countries identified in 2.
- Make sure that each country has available data for each year, if not select another country!
- Use the number of cases of the five countries identified in 2 as the y-Axis
- Label everything and make it look beautiful. 

Thanks for reading.
