---
title: thomaskleiser
author: thomaskleiser
output: html_document
---

```{r, include = FALSE}
# loading the necessary libraries:
library(readr)
library(tidyverse)
library(RColorBrewer)
```


```{r data_importation_manipulation, results = 'hide', warning = FALSE}
# Solution attempt for Jahn's project by thomas:

# importing the data using read_csv()
hiv <- read_csv("C:/Users/thoma/Documents/R/Advanced-data-processing-with-R/Projects/jan-boethling/Data_Project_Jan.csv") %>%
  transmute("country" = Location,
         "year" = Period,
         "cases" = FactValueNumeric) %>% na.omit()

```


```{r excercise_1, results = 'hide', warning = FALSE}
hiv %>%
  group_by(year) %>%
  summarise(cases_per_year = sum(cases)) %>%
  ggplot( aes(x = year,y = cases_per_year/1000000)) +
  geom_bar(stat = "identity", fill = "lightgreen") +
  labs(title = "HIV-cases worldwide",
       y = "cases in milion",
       caption = "source: WHO") +
  theme(plot.title = element_text(face = "bold", hjust = 0.5),
        axis.title.x = element_blank(),
        axis.title.y = element_text(face = "bold"),
        panel.grid.major.x = element_blank(),
        panel.grid.major.y = element_line(color = "grey"),
        panel.grid.minor = element_blank(),
        panel.background = element_blank())

# 2022 was the year with the most HIV-cases.
              
```


```{r excercise_2, rsults = 'hide', warning = FALSE}
hiv_arranged <- hiv %>%
  arrange(desc(cases))

hiv_arranged_top_5 <- hiv_arranged$country %>%
  unique() %>%
  head(n = 5)

hiv %>%
  filter(country %in% hiv_arranged_top_5) %>%
  ggplot(aes(x = year, y = cases/1000, color = country, fill = country)) +
  geom_line() +
    labs(title = "HIV-cases in the countries with the top 5 most cases",
       y = "cases in thousand",
       caption = "source: WHO") +
  theme(plot.title = element_text(face = "bold", hjust = 0.5),
        axis.title.x = element_blank(),
        axis.title.y = element_text(face = "bold"),
        panel.grid.major.x = element_blank(),
        panel.grid.major.y = element_line(color = "grey"),
        panel.grid.minor = element_blank(),
        panel.background = element_blank())

# Over a fifth over worldwide HIV-Cases seem to be coming from South Africa.

```


```{r excercise_3, results = 'hide', warning = FALSE}
hiv %>%
  filter(country %in% hiv_arranged_top_5 &
         year %in% c(2000,2005,2010,2015,2020)) %>%
  ggplot( aes(x = year, y = cases/1000, fill = country)) +
  geom_bar(stat = "identity",
           position = "dodge", color = "black") +
      labs(title = "HIV-cases in the countries with the top 5 most cases",
       y = "cases in thousand",
       caption = "source: WHO") +
  scale_fill_manual(name = "Country", values = brewer.pal(5,"Blues")) +
  theme(plot.title = element_text(face = "bold", hjust = 0.5),
        axis.title.x = element_blank(),
        axis.title.y = element_text(face = "bold"),
        panel.grid.major.x = element_blank(),
        panel.grid.major.y = element_line(color = "grey"),
        panel.grid.minor = element_blank(),
        panel.background = element_blank())

```