---
title: "Enrollment in primary, lower secondary and upper secondary education levels"
author: "Despina"
date: "2024-02-29"
output: md_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```
# About the data
This data set from UNdata contains information about enrollment in primary, lower secondary and upper secondary education levels across the world for females and males.

# Columns explained
Region/Country/Area: place of interest; it can be total, continent, and each country \
Year: The year about which information is given; 2005, 2010, 2015 \
Series: education level measured as students enrolled (thousands) and gross enrollment ration \
Value: number of students enrolled (thousands); gross enrollment ratio for males and females \
Footnotes: "Estimates"; clarification that some of the values are only estimates \
Source: source from which information contained in the dataset was obtained (United Nations Educational, Scientific and Cultural Organization (UNESCO), Montreal, the UNESCO Institute for Statistics (UIS) statistics database, last accessed April 2023)

# What to do
* I don't need the column 'Source'
* The data set is huge and I need to be careful with which rows I want to use, since the 'Series' column contains different measures 

# Visualisation goals
* I would like to compare the gross enrollment ratios of male and female students in different education levels in the same area in one year, and then, how it changed over the years
* I would like to visualise the difference in the gross enrollment ratios between the students in different education levels across countries









