---
title: "Henning's Project Elizaveta's Solution"
author: "Elizaveta Shcherbinina"
date: "`r Sys.Date()`"
output: md_document
---

## OCEAN



```{r include = FALSE}
# Packages and the Dataset

library(readr)
library(dplyr)
library(tidyverse)
library(stringr)
library(ggplot2)
library(cowplot)

df <- read_delim("~/Advanced-data-processing-with-R/Projects/HenningLa7/data.csv", delim = "\t", escape_double = FALSE, trim_ws = TRUE)
```

## Creating a new Dataset for the Graph 

```{r pressure }
df1 <- 
df %>%
    filter(country %in% c("US", "GB", "IN", "AU", "BR")) %>%
    select(-race,-age,-engnat,-gender,-hand,-source) %>%
    group_by(country) %>%
    summarise(      
      O = mean(mean(c_across(O1:O10))), 
      C = mean(mean(c_across(C1:C10))), 
      E = mean(mean(c_across(E1:E10))), 
      A = mean(mean(c_across(A1:A10))), 
      N = mean(mean(c_across(N1:N10)))
      ) %>%
    pivot_longer(cols = 2:6, names_to = "OCEAN") %>%
    mutate(OCEAN = factor(OCEAN, levels=c("O", "C", "E", "A", "N")))

print(df1)

```


```{r echo = FALSE}
# p_dodged_bars <-
df1  %>%
    ggplot(df1, mapping = aes(x = country, fill = OCEAN)) +
    geom_col(aes(y = value), position = "dodge") +
    scale_fill_manual(values = c("#06CDE0", "#7fcdff", "#76b6c4" , "#0A98F2", "#066EC5")) +
    theme_bw() +
    theme(
      axis.title.x = element_blank(),
      legend.position = "none") + 
    labs(y = "Average value of every personality trait",
         title = "Big Five personality traits", 
          subtitle = "for Australia, Brazil, Great Britain, India and United States") +
    scale_x_discrete(labels = c("Australia","Brazil","Great Britain", "India", "United States"))


```


```{r echo= FALSE}
p_letter_old <-
df1 %>%
ggplot(mapping = aes(x = country, fill = OCEAN)) +
geom_col(aes(y = value), position = "dodge") +
scale_fill_manual(values = c("#06CDE0", "#7fcdff", "#76b6c4" , "#0A98F2", "#066EC5"), 
                  labels = c("O", "C", "E", "A", "N"), 
                  name = "OCEAN") + 
facet_wrap(vars(OCEAN), dir = "h") +
theme_bw() +
theme(legend.position = "bottom", 
      # axis.text.x = element_text(angle = -45),
      axis.title.x = element_blank(),
      axis.title.y = element_blank())
# scale_x_discrete(labels = c("Australia","Brazil","Great Britain", "India", "United States"))  + 
# labs(caption = "The following items were rated on a five point scale where 1=Disagree, 3=Neutral, 5=Agree, 0=missed")


```


```{r echo = FALSE}
# p_letter <-
df1 %>%
ggplot(mapping = aes(x = country, fill = OCEAN)) +
geom_col(aes(y = value), position = "dodge") +
scale_fill_manual(values = c("#06CDE0", "#7fcdff", "#76b6c4" , "#0A98F2", "#066EC5"), 
                  labels = c("O", "C", "E", "A", "N"), 
                  name = "OCEAN") + 
facet_wrap(vars(OCEAN), dir = "h") +
coord_cartesian(ylim=c(2.9, 3.5)) +
theme_bw() +
theme(legend.position = "bottom", 
      # axis.text.x = element_text(angle = -45),
      axis.title.x = element_blank(),
      axis.title.y = element_blank())
# scale_x_discrete(labels = c("Australia","Brazil","Great Britain", "India", "United States"))  + 
# labs(caption = "The following items were rated on a five point scale where 1=Disagree, 3=Neutral, 5=Agree, 0=missed")



```

## Horizontal OCEAN Plot
I didnt really like it, so i didnt include it to the final grid. 
```{r echo = FALSE}
df1 %>%
ggplot(mapping = aes(x = country, fill = OCEAN)) +
geom_col(aes(y = value), position = "dodge") +
scale_fill_manual(values = c("#06CDE0", "#7fcdff", "#76b6c4" , "#0A98F2", "#066EC5"), 
                  labels = c("O", "C", "E", "A", "N"), 
                  name = "OCEAN") + 
facet_wrap(vars(OCEAN), ncol = 1) + 
coord_cartesian(ylim=c(2.9, 3.5)) +
theme_bw() +
theme(legend.position = "bottom", 
      # axis.text.x = element_text(angle = -45),
      axis.title.x = element_blank(),
      axis.title.y = element_blank()) +
  scale_x_discrete(labels = c("Australia","Brazil","Great Britain", "India", "United States"))
# labs(caption = "The following items were rated on a five point scale where 1=Disagree, 3=Neutral, 5=Agree, 0=missed")
```

## Final Graph 
After long perfection of the plots, the grid stopped working :_)
```{r}
# grid_plot <- 
# plot_grid(p_dodged_bars, p_letter) + 
#   labs(caption = "The following items were rated on a five point scale where 1=Disagree, 3=Neutral, 5=Agree, 0=missed")
# 
# add_sub(grid_plot, 
#         "This data was collected through on interactive online personality test. 
# O : openness to experience (inventive/curious vs. consistent/cautious) 
# C : conscientiousness (efficient/organized vs. extravagant/careless) 
# E : extraversion (outgoing/energetic vs. solitary/reserved) 
# A : agreeableness (friendly/compassionate vs. critical/rational) 
# N : neuroticism (sensitive/nervous vs. resilient/confident)", 
#         x = 0, hjust = 0, size = 10) %>%
#   ggdraw()

````
