---
title: "ziyi_projekt_second_solution"
author: "Elizaveta Shcherbinina"
date: "`r Sys.Date()`"
output: md_document
---

## How long can you study based on your device \nand internet access?
### Ziyi's Project 



```{r, include = FALSE}
# setwd("/Users/elizavetashcherbinina/Desktop/Vorlesungen/5_Semester/R2 Advanced /Till_Monday_27march")

# Packages 
library(readr)
library(tidyverse)
library(dplyr)
library(ggplot2)
library(stringr)
library(graphics)
library(scales)
library(RColorBrewer)

df <- read_csv("project data.csv")

```


## Data Transformation 

First I cleaned up the data, and what I am really proud of here id the **case_when** function. 

```{r}
final_df <- 
df %>%
  select(P4_1, P4_2, P4_3, S8_1, S8_2) %>%
  drop_na() %>%
  mutate(time_spent = S8_1 * 60 + S8_2) %>%
  mutate(time_spent = as.numeric(time_spent)) %>%
  select(-(S8_1:S8_2)) %>% 
  mutate( code_type =  str_c(P4_1, P4_2, P4_3, sep="_")) %>%
  mutate(type_of_four = case_when(
             code_type == "1_1_1" ~ "Both",
             code_type == "1_2_1" ~ "Only Devices",
             code_type == "2_1_2" ~ "Only Internet",
             code_type == "2_2_2" ~ "None",
           )) %>%
  mutate(time_group = case_when(
             time_spent == 0 ~ "0",
             time_spent <= 120 ~ "0-2",
             time_spent <= 240 ~ "2-4",
             time_spent <= 360 ~ "4-6",
             time_spent <= 480 ~ "6-8",
             TRUE ~ "8+",
           )) %>%
  drop_na() 
```

## The Plot 

I also got some suggestions about changing the usual color palette, so I downloaded a brewer palette and here is the result :) 

```{r echo = FALSE}

# p1 <- 
ggplot(final_df, mapping = aes(x = time_group, fill = type_of_four)) +
  geom_bar() +
  labs(x = "Time Spent on Homework [hours]",
       y = "Number of Students",
      caption = "\n As Devices were considered computers, tablets and smartphones") +
  theme_bw() +
  theme(
    panel.grid.major.y = element_blank(),
    plot.title = element_text(lineheight = 0.9, face = "bold", size=15, hjust = 0)) +
    scale_fill_brewer(name = "Acess to Devices and Internet", palette = "Set2") +
    labs(title = "How long can you study based on your device \nand internet access?")

# ggdraw(add_sub(p1, "\n As Devices were considered computers, tablets and smartphones", x = 0, hjust=0, size = 10))
```


