```{r}
git config pull.rebase false
```

This dataset is a collection of 126 cardiorespiratory data, acquired through wearable sensors from 81 subjects while practicing 10 different sports. Each cardiorespiratory dataset consists of demographic info (gender, age, weight, height, smoking habit, alcohol consumption and\$ weekly training rate), cardiorespiratory signals (electrocardiogram, heart-rate series, RR-interval series and breathing-rate series) and training notes. And here is the link of the website <https://data.mendeley.com/datasets/vtdsszthcw> to download the data.

In this project. I would like to analyze the relationship between the living habits of the subjects (smoke/drink or not), the length of their training and their heart-rate series through visualization. The x-axis represents the training time and the y-axis illustrates the heart-rate series. I would like to use points to stand for every subject. The colours of the points demonstrate whether they drink or smoke. Therefore there will be four colours. Moreover the points are in different forms like squares, circles and triangles, which represent the kind of sports they do. This data set includes 10 kinds of sports, but since we have too few samples in some of them, I only choose BAR, CRO, FIT, MID, RUN and TEN to visualize the data. If possible, I would like to make another plot, in which the color of the point shows the training rate of the subject to visualize the relationship between the training rate, the length of their training and their heart-rate series.
